### ISSUE TITLE
map from tree-data-utils is not working for me

### ISSUE THREAD

**Issue by yhchun1992** [fritz-c/react-sortable-tree#100]
If I provide a callback that doesn't return anything, I get a children of undefined error. The last object it reaches is an object with treeIndex of -1, which was never in my treeData in the first place. Seems like it created it by itself, and assigned the root of my original treeData as its children.

Maybe I'm using the method incorrectly, could you provide an example of how to use it?

**Comment by fritz-c** [comment]
There's a chance I didn't account for a map result returning nothing. Have you tried returning an empty array?

**Comment by brentjm** [comment]
I'm having a similar problem. The map function is calling the callback on all the nodes then gives a TypeError on the node following treeIndex of -1.  Here's my function:

```
import SortableTree, { addNodeUnderParent, removeNodeAtPath, changeNodeAtPath, getNodeAtPath, toggleExpandedForAll, defaultSearchMethod, map as mapTree } from "react-sortable-tree";

fillNodeData(simulationParameters) {
        try {
            var node = mapTree({
                treeData: initialTreeStructure,
                getNodeKey: ({node: TreeNode, treeIndex: number}) => {
                    return number;
                },
                callback: (param) => {param.node.subtitle="test"; console.log(param); return param},
                ignoreCollapsed: false
            });
        }
        catch (e) {
        }
        console.log(node);
        return node;
    }
```

![error](https://user-images.githubusercontent.com/7213849/27558762-478501ee-5a8c-11e7-8c4f-84918bb8f1b2.png)

**Comment by brentjm** [comment]
I'm probably missing something on the map function, but was able to get the walk function to update the nodes. I passed the walk function the state - treeData object, and called changeNodeAtPath with treeData from the state object. Here's the code that worked for me.
```
    fillNodeData(treeData, simulationParameters) {
        walk({
            treeData: treeData,
            getNodeKey: ({node: TreeNode, treeIndex: number}) => {
                return number;
            },
            callback: (rowInfo) => {
                if (rowInfo.node.hasOwnProperty("getSubtitle")) {
                    rowInfo.node.subtitle = rowInfo.node.getSubtitle(this.props.simulationParameters);
                    treeData = changeNodeAtPath({
                        treeData: treeData,
                        path: rowInfo.path,
                        newNode: rowInfo.node,
                        getNodeKey: ({ treeIndex }) =>  treeIndex,
                        ignoreCollapsed: false
                    });
                }
            },
            ignoreCollapsed: false
        });
    }
```
