### ISSUE TITLE
I have some questions about adding child elements and deleting.

### ISSUE THREAD

**Issue by Ccheng2729111** [fritz-c/react-sortable-tree#106]
so sad.

**Comment by Ccheng2729111** [comment]
Another problem is how to change it to Input.
I want it to be input.

Can you help me with that

**Comment by Ccheng2729111** [comment]
@fritz-c

**Comment by fritz-c** [comment]
Check out the storybook linked in the readme for examples of adding/removing nodes, as well as displaying modifiable inputs.
