### ISSUE TITLE
Dragging external wrapped object to sortable tree

### ISSUE THREAD

**Issue by vincentlee248** [fritz-c/react-sortable-tree#107]
I am trying to wrap my own object into drag resource so that i can drag that external object to sortable tree directly with preview. I am currently having an issue that if i specify a dndtype as prop to sortable tree, once i drag the external object over to the tree, the draggingTree state will be overwritten completely and the treeData won't get update as expected. I wonder what's the difference between dragging a node from inside the tree and outside the tree. I looked inside the source code, can't really figure that out.

**Comment by vincentlee248** [comment]
@ncphillips

**Comment by fritz-c** [comment]
Can you try out

**Comment by fritz-c** [comment]
Whoops. Try out the example in the storybook linked from the readme? I have a simple implementation of external nodes there.

**Comment by vincentlee248** [comment]
Have already tried it and It works really well on our side now. Thanks
