### ISSUE TITLE
Added typings

### ISSUE THREAD

**Issue by wouterhardeman** [fritz-c/react-sortable-tree#108]
Hey there,

First off, thanks for making this component. It helped me out a lot!

I took the liberty of adding types in the DefinitelyTyped repository. You can find them [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17488). You can review them if you want. If you prefer having the types in your own repository, let me know and I will close the pull request.

**Comment by fritz-c** [comment]
Wow, that's awesome! Thank you for putting that together. I think I've had other people asking for types before, and now I know where to point them!
