### ISSUE TITLE
How to implement a case-insensitive searching ?

### ISSUE THREAD

**Issue by LogicMonsters** [fritz-c/react-sortable-tree#112]
Any thoughts on that ?

**Comment by fritz-c** [comment]
Is the default search callback not already case-insensitive? If not, take the code from the default one and use `.toLowerCase()` on both sides of the comparison.

**Comment by LogicMonsters** [comment]
Yes, it is not. And thanks for your help ！

**Comment by oarashi** [comment]
@LogicMonsters can U please describe how U fixed this issue? I cannot find out the best solution. Thanks in advance.
