### ISSUE TITLE
Is there a way to get original position/path via onMoveNode() ?

### ISSUE THREAD

**Issue by LogicMonsters** [fritz-c/react-sortable-tree#116]
Thanks for this great component ! 
As the title, do you consider adding "prevPath" in onMoveNode callback ? Just like what we have in the canDrag/canDrop callback. Since it would be great to know where the node come from.

**Comment by rrhvella** [comment]
Related pull request:  #123

**Comment by fritz-c** [comment]
Those parameters are now provided to the callback as of version 1.0.0.
