### ISSUE TITLE
Weird console.log in the code

### ISSUE THREAD

**Issue by sapegin** [fritz-c/react-sortable-tree#119]
Does [it have any purpose](https://github.com/fritz-c/react-sortable-tree/blob/e58083fb28b640deb9d33dd8ba5b689096697421/src/react-sortable-tree.js#L209) or I can send a PR to remove it?

```js
console.log('ctodo((((varName2))))'); // eslint-disable-line no-console
```

**Comment by fritz-c** [comment]
Oh, crap. Thanks for pointing it out. I can take care of it.

**Comment by fritz-c** [comment]
Should be taken care of in v0.1.21.
Sorry it took a while - I had neglected my build process for a while and it revolted. Tests were failing for no reason, so I had to move to Jest along with a few other things
