### ISSUE TITLE
Add title attribute to title

### ISSUE THREAD

**Issue by darrensw777** [fritz-c/react-sortable-tree#120]
Because of the nature of things this could be used for, some of the titles could get long. What I'd like to do is to add ellipsis to the node title, which I can do with css easily, but, how can I also add the node title, to the title attribute for the title element e.g.

`<span class="rst__rowTitle" title="My Title">My Title</span>`

Is this possible?

**Comment by stephenc222** [comment]
With the current implementation, I would say that it _is_ possible to pass the node title as the title attribute for each node, as long as you pass in a custom NodeContentRenderer prop to react sortable tree, and add in the returned JSX of the render function for NodeContentRenderer the title HTML5 standard attribute recognized by JSX. Example here, and you can find this (minus the title attribute stuff and comments) on [L139](https://github.com/fritz-c/react-sortable-tree/blob/master/src/node-renderer-default.js#L139) of the default NodeContententRenderer Component:

```
<span 
   className={ 
     // the "rst__rowTitle" class is how RST's webpack config compiles CSS module classes
     styles.rowTitle + (node.subtitle ?  ` ${styles.rowTitleWithSubtitle} ` : '') 
   }
   // add your title HTML5 attribute here:
   title={node.title}
>
   {typeof node.title === 'function' ? node.title({ node, path, treeIndex }): node.title}
</span>

```

I would suggest copying over the current NodeDefaultRenderer.js file, and start with small modifications to it, like adding the title attribute to a span tag.

**Comment by fritz-c** [comment]
For simplicity's sake, I would recommend avoiding the `customNodeRenderer` if you can help it.
In your nodes, I would recommend setting `title` to an element with the properties you describe, and the raw text as a different property in the node.
For example:
```js
{
  title: (
    <div
      style={{
        width: 200,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
      }}
      title="My Title"
    >
      My Title
    </div>
  ),
  rawTitle: 'My Title',
}
```

**Comment by fritz-c** [comment]
In `v1.1.0` I added props to the `defaultNodeRenderer` that would allow you to override the title part of the node without having to put react elements into your js objects. 
Take a look at the "Modify Nodes" example and its source to get an idea of how to use it:
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Modify%20nodes&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel
