### ISSUE TITLE
TypeError: __webpack_require__.i(...) is not a function when importing dndWrapExternalSource

### ISSUE THREAD

**Issue by derekduoba** [fritz-c/react-sortable-tree#124]
As the title says, I'm encountering this type error when I attempt to import dndWrapExternalSource. It appears that dndWrapExternalSource isn't defined, possibly indicates that the function simply isn't being imported.

I am able to import other utility functions, such as addNodeUnderParent, without problems. However, I am not able to import *any* functions from drag-and-drop-utils.

Version(s): 0.1.21 and 0.1.19 using the npm package.

**Comment by fritz-c** [comment]
Were you able to resolve this? I tried to reproduce it in my local environment and didn't get anywhere.

**Comment by derekduoba** [comment]
It seems it was an issue with the way I was importing. I tried another method, which worked fine. I'll close this out for now.
