### ISSUE TITLE
Is there a way to remove an node by dragging?

### ISSUE THREAD

**Issue by Jarvis1010** [fritz-c/react-sortable-tree#128]
I have a tree of Items and I have successfully made it so I can drag and drop new nodes in the tree. I was hoping I could do the inverse by dragging an item out of the tree to remove it.  Is this supported?

**Comment by fritz-c** [comment]
I put together an example here: ["Drag out to remove"](https://fritz-c.github.io/react-sortable-tree/storybook/index.html?selectedKind=Advanced&selectedStory=Drag%20out%20to%20remove&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel)
