### ISSUE TITLE
Prefix css classes to avoid collisions

### ISSUE THREAD

**Issue by jkrentz** [fritz-c/react-sortable-tree#129]
Adding the lib to an existing project using the bootstrap grid results in name collisions on the `row` class. It's easy to imagine situations where `node` and `tree` may collide with other libraries as well.

**Comment by stephenc222** [comment]
I am currently working on a drag and drop editor plugin to give a non-sophisticated user the ability to build complex forms for their website for a client, in the plugin-rich wordpress environment. The client-side of the form editor I'm building is written purely with React and uses react-sortable-tree for handling drag and drop within a hierarchical tree data structure, and this prefixing of CSS classes is also a concern I have as well.

**Comment by fritz-c** [comment]
I believe the code post-build prefixes every class with `rst__`. Are you doing something special in your build to bypass the CSS module compilation?

**Comment by fritz-c** [comment]
Let me check this once I get home. It's possible I'm importing some CSS that includes `.row`.

**Comment by buzztone** [comment]
Is it also possible for the prefix to be customized, when we use this package, to avoid potential CSS conflicts with others using RST in another WordPress plugin and using different CSS styling for the ```rst_``` classes.

**Comment by fritz-c** [comment]
@jkrentz I checked on my demo site, and I didn't find any class defined for `.row`, only `.rst__row`. Can you give me the link to a repo demonstrating the collision, or an explanation of how to set it up?

@buzztone The prefix is baked in whenever the library is built. I think it would be up to the plugin creator to "namespace" their customizations by using a different class for the outermost container, something like `.my-package-tree .rst__node { background: #000; }`.

**Comment by stephenc222** [comment]
I'm using normal CSS module compilation and your answers are exactly what I knew you would say. This concern I mentioned is only a possible concern for the future, and using multiple CSS class names in essentially guaranteeing the CSS of RST stays unalterable, even if requiring copying over the RST CSS rules to multiple CSS class selector rules, is exactly what I was intending to do. Thanks for response!
