### ISSUE TITLE
Consistency of method return type (removeNodeAtPath)

### ISSUE THREAD

**Issue by geniot** [fritz-c/react-sortable-tree#13]
Maybe not a bug but an idea.
I'm looking at https://github.com/fritz-c/react-sortable-tree/blob/master/src/utils/tree-data-utils.js
Most methods that manipulate the tree return associative arrays.
Except these:
removeNodeAtPath - {Object} changedTreeData
getNodeAtPath
getTreeFromFlatData  {Object[]} treeData
insertNode - returns associative array but it is not documented

I was trying to set the state after manipulation but insertNode and removeNodeAtPath return different object types. So it took a while to realize it should be: 
setState(insertNode(...))
and 
setState({treeData:removeNodeAtPath(...)})
Thanks.

**Comment by fritz-c** [comment]
I apologize for tripping you up. When I was making those APIs I was mainly looking at them from the viewpoint of what I needed at the time. However, I wouldn't recommend an approach like `setState(insertNode(...))` in any case, because I might add some (helpful) junk to the returned object in the future.

Do you think improved util API documentation could have helped avoid the confusion? I'm leaning towards doing that in the near future anyway. An API alteration would mean some people would have to go back and fix their code, so it's kind of a tradeoff.

**Comment by geniot** [comment]
No worries. It is just a suggestion. I'm very grateful to you for this component. It saved me like months of work (I'm a beginner in ReactJS). Just thinking how tree dnd can work makes my brain twist. 
As to your questions, I think you are right. Changing API now would make users unhappy. Adding another API on top would confuse the things. Personally I'm not a big fan of reading documentation, I intuitively expect things to work consistently. 
I would extend the example by adding use cases for other API methods (insert, remove, to/from flat tree, etc.) And documentation wouldn't be necessary in this case. Also a use case for a custom renderer with some edit functionality inside would be nice.
In fact if you are interested I can do this and send it to you (I'm not sure how to do it correctly with gibhub tools).

**Comment by fritz-c** [comment]
Thank you for the feedback. I'm happy to hear that I could save you time.

I'm not sure about making the main example any more complicated than it is, but examples do seem like a good way to explain the usage. If you have something you've written already, I'd be interested in seeing it, but don't trouble yourself if you haven't. I'm not confident that I could get the demo site working with several examples right away, so I'll either put it off until I can, or opt for a simpler, markdown document example.

**Comment by absolutelysimon** [comment]
While this is still the first google result for "removeNodeAtPath" I just wanted to add to the record that this change was implemented and "removeNodeAtPath" now returns treeData.
