### ISSUE TITLE
Drag from react-sortable-tree to another source (e.g. React-dnd, another react-sortable-tree)

### ISSUE THREAD

**Issue by oarashi** [fritz-c/react-sortable-tree#132]
@fritz-c Is there a possibility to drag node from react-sortable-tree into another source (e.g. React-dnd, another react-sortable-tree)?
Thank you!
P.S. Great library! =)

**Comment by fritz-c** [comment]
Works now in versions `>=1.0.0`

**Comment by fritz-c** [comment]
See the storybook linked in the readme to find examples of tree-to-tree or arbitrary react-dnd source to tree.
