### ISSUE TITLE
Changing color of the vertical and horizontal connector lines

### ISSUE THREAD

**Issue by sabhyankarxactly** [fritz-c/react-sortable-tree#136]
Hello,

Is there a way to change the color of the lines that connect the nodes of the tree? Using a custom node renderer I was able to change the border color of the node but I want to get that same color on the lines as well. The lines have CSS classes like .rst__lineFullVertical:after, .rst__lineHalfVerticalBottom:after, .rst__lineHalfVerticalTop:after which have a background-color style that can be updated to the color I want to change the color of the connecting line. I can do this from the browser developer tools to get the desired effect, but how do I change it from my code?

**Comment by fritz-c** [comment]
Perhaps you could add some CSS rules for the selectors you've described into your own CSS file.

**Comment by codetony25** [comment]
The selectors below is what i've used to overwrite the line colors:

```
.rst__lineHalfHorizontalRight::before, 
.rst__lineFullVertical::after,
 .rst__lineHalfVerticalTop::after,
.rst__lineHalfVerticalBottom::after,
.rst__lineChildren::after {
  background: pink;
}
```

**Comment by sabhyankarxactly** [comment]
Thanks, this is what I tried out and it worked.
