### ISSUE TITLE
Dragging external item to sortable tree without elements

### ISSUE THREAD

**Issue by svsool** [fritz-c/react-sortable-tree#137]
Hi, is it possible to drop external item to [tree without elements](https://monosnap.com/file/6yRWu1v3GNOUwsSpJypNYohf5r5IC3)? Should it render drop area (placeholder) to accept external items or this case should be handled by user?

**Comment by fritz-c** [comment]
This is solved in versions 1.0.0 and above, thanks to a placeholder element for empty trees.

**Comment by dharanidhanapalan** [comment]
Hi , is there any option to drag an item from react sortable tree to external element (like div) ?  Should we add drop area in the div to accept the item, if it so please share the drop area method? or else is there any different approach? 

Thanks!

**Comment by svsool** [comment]
Yes, it's exactly what I want, thanks!
