### ISSUE TITLE
Is it possible to force the tree to fully expand on a render?

### ISSUE THREAD

**Issue by garrettlr** [fritz-c/react-sortable-tree#144]
Hello,

The title pretty much says it all, but I'm looking for a way to force the tree open whenever a render occurs. 

Thanks!

**Comment by fritz-c** [comment]
There's a util function to do that called `toggleExpandedForAll`. You can see it in action on the main demo site, the source code of which is here:
https://github.com/fritz-c/react-sortable-tree/blob/master/examples/basic-example/app.js

**Comment by garrettlr** [comment]
Awesome, Thank you!
