### ISSUE TITLE
Inline edit of node title not working anymore?

### ISSUE THREAD

**Issue by rgeike** [fritz-c/react-sortable-tree#146]
Hi,
we are using the react-sortable-tree. Now we want to enable users to edit the title of a node. You have shown an example at modify-nodes.js. Unfortunately this does not seem to work anymore?
We updated our npm package to 1.21 and still get no chance to edit the title. When we hit the console we see an object inside the title property. Tough it should be in the rowTitle-span-Element.
Any ideas are appreciated!
Thanks, Richard

**Comment by fritz-c** [comment]
Could you make sure the version is 1.1.0 or greater?

**Comment by rgeike** [comment]
Thanks, we updated manually to the latest version. That made the trick!
