### ISSUE TITLE
How to use getTreeFromFlatData method. ---Not an issue. Just a Doubt

### ISSUE THREAD

**Issue by gmarathi-nisum-com** [fritz-c/react-sortable-tree#149]
Hi,
Thank you for this Component.It is very usefull.

I have a json data in the format as below

"Data":  [{
 	"id": 2,
 	"name": "Parent1",
 	"acronym": null,
 	"parentId": null,
 	"child": [{
 		"id": 4,
 		"name": "child1",
 		"acronym": "ABC",
 		"parentId": 2,
 		"leaf": [{
 				"id": 2,
 				"acronym": "ALLUUI",
 				"name": "leafNode1"
 			},
 			{
 				"id": 4,
 				"acronym": "LGGM",
 				"name": "LeafNode2"

 			}
 		]

 	}]
 ,{......},{....}
]

How can i use the getTreeFromFlatData method to get the object structure required for treeData?

**Comment by fritz-c** [comment]
I added a [new example to the storybook, called treeData import/export](https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=treeData%20import%2Fexport&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel) demonstrating how to use the `getTreeFromFlatData` function. The source is available too. Does that help answer your question?

**Comment by gmarathi-nisum-com** [comment]
thanks

**Comment by aterentev** [comment]
Hi fritz-c,
How can I import method getTreeFromFlatData into my project? In your example you just imported it from '../../src', but I can't do the same. I found this method in bundle file, but I can't get it.

**Comment by khaledbk** [comment]
@kemo71 i suggest you to pass your props with componentWillReceiveProps(newProps) not with (createContainer) and in this method you can init your state with the new (treeData) passed from the other components ..
in every update you get for the new treeData (from the props) , it will update your state and you can always render your [treeData] from the state (because its reactive) ..

**Comment by pawurb** [comment]
@fritz-c is your example still available somewhere ? Link does not seem to work anymore

**Comment by dolezel** [comment]
https://frontend-collective.github.io/react-sortable-tree/?selectedKind=Basics&selectedStory=treeData%20import%2Fexport&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

**Comment by shahlav** [comment]
> I added a [new example to the storybook, called treeData import/export](https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=treeData%20import%2Fexport&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel) demonstrating how to use the `getTreeFromFlatData` function. The source is available too. Does that help answer your question?

Does this example still available at any place?
It returns 404 😕

**Comment by psorensen** [comment]
Hi Friends. The example @fritz-c  was referring to is here: https://github.com/frontend-collective/react-sortable-tree/blob/52f0bcf51a80297ab63d5d1cfb0b32f4e3f0e702/stories/tree-data-io.js#L17-L24

I also tripped here, thinking the method accepted an array. Be sure to pass an object with the correct keys, not just the flat array.
