### ISSUE TITLE
Provide sibling node in onMoveNode callback

### ISSUE THREAD

**Issue by NishantDesai1306** [fritz-c/react-sortable-tree#153]
First of all thanks for an awesome component like this. I am facing an issue with the drag and drop.

Please provide a new information about the sibling in `onMoveNode` callback.
Assume that I have moved a node(`n`) inside a sub tree which was initially located at root level

- a
- b
- n (node dragged from here)
- subParent
    - subChild1
    - n (node dropped here)
    - subChild2
- c
- d

now without sibling information how will I know the index of dropped node(`n`) in `subParent` ? (in this case the index of `n` in `subParent` is 1).

if developers can have information about sibling (in this case information of node `subChild1` then by using `id` or something one can figure out the index of dropped node in new parent).

although the callback does provide the `previousIndex` and `nextIndex` but these indices are calculated from root of the tree whereas my usecase needs the index of moved node inside new parent

**Comment by NishantDesai1306** [comment]
I have solved it for now by using the `getFlatDataFromTree({treeData})[newIndex - 1]`, but it would be great if you can just provide the sibling's info in onMoveNode callback

**Comment by wuweiweiwu** [comment]
@fritz-c I can take this!

**Comment by fritz-c** [comment]
@wuweiweiwu Yeah, let's start with just providing the parent node.

**Comment by fritz-c** [comment]
@NishantDesai1306 the `nextParentNode` (which contains all the siblings of the node as well as the moved node in its children) is now included in the `onMoveNode` callback in `v1.8.1`, thanks to @wuweiweiwu!
