### ISSUE TITLE
nodeContentRenderer issues

### ISSUE THREAD

**Issue by shalinigr** [fritz-c/react-sortable-tree#154]
Hi!
I have been trying to customize the node in order to support onHover and onClick and other functionalities for each node. I tried copying the node-renderer-default.js file as suggested and added my onClick event. The event still doesn't fire and I'm unsure if it needs to be implemented elsewhere. I would really appreciate some guidance!

**Comment by dharanidhanapalan** [comment]
Hi, 
You can write the onClick function for the node in generateNodeProps property.

generateNodeProps={rowInfo => ({
    onClick: () => console.log(1),
})}

And also you can refer #74

**Comment by shalinigr** [comment]
Thank you @dharanidhanapalan ! it works!
