### ISSUE TITLE
Window is not defined react-sortable-tree/dist/main.js:1080

### ISSUE THREAD

**Issue by olavidps** [fritz-c/react-sortable-tree#159]
Hello I have this problem, 5 days ago The library worked fine, but today I'm trying to run 'npm run dev' in my project, and gives me this error.. (I have reinstalled through npm and it doesn't work)

![image](https://user-images.githubusercontent.com/2839242/30300090-6fdb4f0e-9718-11e7-8b7a-0d8b9f56c8eb.png)

**Comment by olavidps** [comment]
This was solved replacing:

`import { SortableTree } from 'react-sortable-tree'`
with
```
const isBrowser = typeof window !== 'undefined'
const SortableTree = isBrowser ? require('react-sortable-tree').default : undefined
```

**Comment by nasushkov** [comment]
Hi, I've got the same issue. If this component is supposed to be used with SSR I suppose this is a bug.
