### ISSUE TITLE
Problem with react-dnd dependency

### ISSUE THREAD

**Issue by NataGrankina** [fritz-c/react-sortable-tree#161]
Hello.

Firtst of all, thanks for such a great library.

I faced the following problem while installing your library to my project. Your library needs react-dnd@">=2.0.0 <=2.4.0", but react-dnd-html5-backend@2.5.1 needs react-dnd@^2.5.1 so npm install fails.
Maybe it would be better to use strict version in package.json instead of using caret ranges to avoid such collisions?

Thanks in advance.

**Comment by fritz-c** [comment]
Thanks for the heads-up. I released what I hope is a fix with v1.2.2, in which I gave both `react-dnd` packages strict versions.

**Comment by NataGrankina** [comment]
Thank you, the issue is solved.
