### ISSUE TITLE
rst__Node styling issues

### ISSUE THREAD

**Issue by shalinigr** [fritz-c/react-sortable-tree#163]
I have been trying to change the styling of rst__node from generateNodeprops but it reflects only on rst__row. The className, onClick and others. I need to change the background color and capture clicks on the whole of rst__node and not just the rst__ row. I am able to get the whole node on hover but not other properties. Any suggestions? @fritz-c  is this possible?

**Comment by dharanidhanapalan** [comment]
Hi even i need the same.

**Comment by dharanidhanapalan** [comment]
@shalinigr Did you find any solution for this?

**Comment by shalinigr** [comment]
@dharanidhanapalan  No. I haven't been able to achieve it. Not sure if there's a css selector like :hover that I could use when it's clicked and they all share the same className.

**Comment by yogeshtiwari1990** [comment]
you can create your custom node component with all required customizations and render using nodeContentRenderer prop.

**Comment by shalinigr** [comment]
@yogeshtiwari1990 The custom component will apply the styling to every node since the tree adds the same classname and there is no id to differentiate. I need to change the node on selection. Please correct me if I'm missing something.

**Comment by dharanidhanapalan** [comment]
@shalinigr  Try this 
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Playing%20with%20generateNodeProps&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

This may help you .

**Comment by yogeshtiwari1990** [comment]
@shalinigr with custom node component you can also create its separate CSS file.  And in that have different classes for all colors you require. And based on props sent to this component via generateNodeProps option you can switch between colors. Can also use a prop to capture click on each node.

**Comment by rheinheimer** [comment]
@shalinigr Like others suggested, using a custom node renderer is the way to go. I added an "active" property to the node, and then the following to my custom renderer className:
```
(node.active ? ` ${styles.activeRow}` : '')
```
The ".activeRow" is a new style in the scss, and could be whatever you want. The node is selected/activated by using an onClick on either a button or the entire node div, passed in through the generateNodeProps. I'm working on this problem right now and would be happy to share my code once I get it working smoothly.

HOWEVER, this may not address the original issue of wanting to change the higher level rst__node, which seems to span the entire width of the tree. I'm not sure how you would get there.

**Comment by shalinigr** [comment]
@dharanidhanapalan @yogeshtiwari1990 @rheinheimer thank you guys! I tried using the custom renderer and have it working.

**Comment by shalinigr** [comment]
@rheinheimer It would be great if you could share your code. I just wanted to make sure of the usage and if I could better it.

**Comment by dharanidhanapalan** [comment]
@shalinigr I don't know how to use the custom node component. If you have used the custom node component. Can you please share the code? It will be helpful for me. 

Thanks

**Comment by dharanidhanapalan** [comment]
@shalinigr  Did you change the height of rst__node class? Even I tried with nodeContentRenderer property, but I am able to do that? can you tell how you changed that ? Please share me sample code.

Thanks.

**Comment by yogeshtiwari1990** [comment]
@dharanidhanapalan I believe you can use the rowHeight prop for this. By default it is 62.

**Comment by dharanidhanapalan** [comment]
@shalinigr Ya I set rowHeight. Can rowHeight be set dynamically according to parent and child nodes? If so can you tell me in which function we should set that ?

Thanks

**Comment by shalinigr** [comment]
@dharanidhanapalan rowHeight can be set at the tree level like

<SortableTree
treeData = {treeData}
rowHeight = {40}
.....>

It applies to the whole tree.

**Comment by dharanidhanapalan** [comment]
Okay Thanks

**Comment by superpam33** [comment]
Hi, there's lots of good discussion here and sounds like some folks have successfully got it working! Yay! Can @shalinigr or someone please share the love and share some of your lovely code with me on how you guys got the nodeContentRenderer prop working properly? Really appreciate it.

**Comment by Manali-addweb** [comment]
Hi, please share your code or any other solution if anyone has a working solution for this issue.
