### ISSUE TITLE
How to import this to another project?

### ISSUE THREAD

**Issue by edargham** [fritz-c/react-sortable-tree#164]
Kinds still a noob in using react and web development, and I would like to use this implementation of a tree for my project, can you tell what do I need to do??

**Comment by fritz-c** [comment]
I'm assuming you're using something like create-react-app to give you a good base for building an app on. Once you have a project with a package.json file in the base directory, run `npm install --save react-sortable-tree` to download the library. Then you can `require` or `import` the library into your app wherever you're using JSX, and plug it in your `render` function. The sample code in the README is a good first boilerplate for the tree.

**Comment by edargham** [comment]
Okay, so installed the package and I pasted the code found on the Readme Page in a js file, but when I'm executing it, it returns this error:

`ReferenceError: Can't find variable: exports`

How can I solve this??

`import React, { Component } from 'react';
import SortableTree from 'react-sortable-tree';

export default class Tree extends Component {
  constructor(props) {
    super(props);

    this.state = {
      treeData: [{ title: 'Chicken', children: [ { title: 'Egg' } ] }],
    };
  }

  render() {
    return (
      <div style={{ height: 400 }}>
        <SortableTree
          treeData={this.state.treeData}
          onChange={treeData => this.setState({ treeData })}
        />
      </div>
    );
  }
}`

**Comment by fritz-c** [comment]
Hm. Make sure you have something like webpack/gulp/create-react-app to transpile your code. 
If all else fails, Google it.

**Comment by edargham** [comment]
Yeah, I did that and it work but I still have one minor issue, is the same way I should follow in order to import the  extra features you displayed on storybook?
