### ISSUE TITLE
Media to nodes drop

### ISSUE THREAD

**Issue by edgesoft** [fritz-c/react-sortable-tree#168]
I'm looking at this and it looks very promising. I have created my own tree that supports drag and drop but not super happy about it and now I came across this. I just have a question on supporting other dropTargets. I want to be able to drop other stuff in but not create new child it should basically allow dropping on the nodes. Is this possible?

**Comment by fritz-c** [comment]
You could use the `generateNodeProps` prop to assign a custom component to the `title` prop that has its own react-dnd bindings. Fiddle with the css of your component and you should be able to make it cover the whole node.

Here's an example to get you started with using `generateNodeProps`:
[Playing with generateNodeProps](https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Playing%20with%20generateNodeProps&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel)  ( [source](https://github.com/fritz-c/react-sortable-tree/blob/master/examples/storybooks/generate-node-props.js) )
