### ISSUE TITLE
SortableTree fails to render items when wrapped by a `div`

### ISSUE THREAD

**Issue by ncphillips** [fritz-c/react-sortable-tree#17]
I can get around this by using `span`s, but this strange bug should definitely be looked into.

**Comment by fritz-c** [comment]
Thank you for the bug report.
Could you provide some more details about the circumstances in which this occurred?
Sample code, browser / OS version, presence of console errors, etc.

**Comment by ncphillips** [comment]
Sorry for the late reply. 

Even using spans, it seems like it doesn't work at all in safari.

* No console errors.
* Chrome 54, and Safari 9.1.3

I have a gut-feeling it's a CSS issue, because I don't think there's anything particularly weird going on in the React components. Here's what the resulting DOM in safari.

![image](https://cloud.githubusercontent.com/assets/824015/20499311/5a6297ca-b007-11e6-83b6-3d0e7281b45e.png)

**Comment by ncphillips** [comment]
By comparison here's the DOM of this exact form in Chrome, where it is working.

![image](https://cloud.githubusercontent.com/assets/824015/20499480/0846b8d0-b008-11e6-8b74-2dc416c0e137.png)

**Comment by ncphillips** [comment]
Could this be a `react-virtualized` bug?

**Comment by fritz-c** [comment]
Try including the css from `react-virtualized` in your style, as described in the [react-virtualized README](https://github.com/bvaughn/react-virtualized).

**Comment by ncphillips** [comment]
Unfortunately that did not help :/

**Comment by mcyze** [comment]
If you think it is the will-change css, then override it on the r-v component with something like: styles={{ willChange: "auto !important" }}.  That fixed my problem, anyway.

**Comment by ncphillips** [comment]
Thanks @mcyze, but that didn't work, so I guess it might not be related to that. 

I just got into `react-virtualized` and noticed that in Safari the `Grid` component is ending up with an empty array for [`_childrenToDisplay`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L540)

It looks like this is being caused by a [check of the height and width](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L616). It seems that, in Safari, the height is being set to 0.

**Comment by ncphillips** [comment]
Yahs!

The issue is that the surrounding `div` had a height of `0` initially. By forcing a height on the surrounding div, this bug is solved. This might be something to add to the docs.

![image](https://cloud.githubusercontent.com/assets/824015/20528843/226eddf4-b0a4-11e6-887c-5c98056c747f.png)

**Comment by fritz-c** [comment]
Sorry for the inconvenience. I'm glad you got it figured out.

For the time being, I've added a wrapping div with a fixed height to the example in the README, which I think will reduce the chance of this coming up again.

**Comment by anil1712** [comment]
@ncphillips Can you please share your `NodeRenderer` code. 
I did not find any sample code in doc to achieve this. So its better if you can provide some simple snippted. Actually my tree data json has different `key` (instead of `title` and `children`) so I have to use `nodeContentRenderer`. 

Please help me to out of it.

Thanks,
Anil
