### ISSUE TITLE
Error: Cannot call hover after drop

### ISSUE THREAD

**Issue by yogeshtiwari1990** [fritz-c/react-sortable-tree#171]
First of all Thanks for such awesome component.
I was trying to implement drag and drop between trees and found a breaking issue. 
It can be reproduced [here](https://www.webpackbin.com/bins/-Kv7po4FvCaPqEnYjkCG)

Whenever  I try to drag a node from the first tree and drop as a child node on the second tree it logs following error on console : 
VM183 main.js:147 Uncaught TypeError: Cannot read property 'checked' of undefined
    at Object.onChange (VM183 main.js:147)
    at ReactSortableTree.value (VM182 dll.js:25)
    at Object.endDrag (VM182 dll.js:25)
    at Source.value (VM182 dll.js:25)
    at DragDropManager.endDrag (VM182 dll.js:25)
    at Object.endDrag (VM182 dll.js:25)
    at HTML5Backend.value (VM182 dll.js:25)
onChange @ VM183 main.js:147
value @ VM182 dll.js:25
endDrag @ VM182 dll.js:25
value @ VM182 dll.js:25
endDrag @ VM182 dll.js:25
(anonymous) @ VM182 dll.js:25
value @ VM182 dll.js:25

After that Drag operation gets disabled. Even if we try to drag a node it throws below error : 
VM182 dll.js:6 Uncaught Error: Cannot call hover after drop.
    at invariant (VM182 dll.js:6)
    at DragDropManager.hover (VM182 dll.js:25)
    at Object.hover (VM182 dll.js:25)
    at HTML5Backend.value (VM182 dll.js:25)

And the same thing also happens when I get an error "No node found at the given path." from changeNodeAtPath function.

Can we somehow make sure that even in case of error the dnd functionality does not break? 
Not sure but we can try to End the old drag if call beginDrag while dragging.

**Comment by fritz-c** [comment]
Thank you for making the webpackbin example. It made it a lot easier to check out this report.

I think the issue is that you have the `onChange` handler of a checkbox being used as the `onChange` handler of the tree. Therefore, when you reference `event.target.checked`, it throws the error you mentioned. Modify it to update `treeData1` instead, as demonstrated here, and it should work: https://www.webpackbin.com/bins/-Kv9tF31Nq5BW80CqyZZ

**Comment by yogeshtiwari1990** [comment]
Sorry for not explaining it properly. I created that scenario to fail.
I am implementing drag and drop between two trees. And while dragging from one tree to attach as a child in another the function changeNodeAtPath is throwing the error  "No node found at the given path." which I am still investigating.

But the issue is drag and drop stops working after that and continuously logs error "Cannot call hover after drop."
Can we somehow make it more robust that dnd functionality does not break even in case of error?
