### ISSUE TITLE
How to add a sibling node for a given node?

### ISSUE THREAD

**Issue by xgzl87** [fritz-c/react-sortable-tree#172]
![image](https://user-images.githubusercontent.com/12945325/31005119-efaabe1c-a529-11e7-8207-07f20d9c15df.png)
add more button  is to add the root node

**Comment by fritz-c** [comment]
https://codesandbox.io/s/0p1p1jzrx0

**Comment by xgzl87** [comment]
Thank you, then add the parent node?

**Comment by borisyordanov** [comment]
@xgzl87 One way to do it is to clone the clicked node as a sibling to the parent - https://codesandbox.io/s/vywxjmvpqy and then delete the clicked node.

**Comment by wuweiweiwu** [comment]
Seems like this has been resolved :)
