### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by oarashi** [fritz-c/react-sortable-tree#175]
Hi! Thanks for the great library!
I run into a real problem with path. The thing is path is changing depends if upper elements collapsed/expanded.
Example:
I have element with some nested element in it (ELEM_1) and under it (on the same level) there is another element (ELEM_2). When ELEM_1 is collapsed the path of the ELEM_2 is [2], but when ELEM_1 expands path of the NODE changing to [7]. 
The thing is I'm synchronizing with backend on changing node position and I need to save new position path. But because of it behavior (changing path depends on other elements collapsed/expanded) I have really serious problems.
Is there any way to handle it?
Thanks!

**Comment by fritz-c** [comment]
Use the `getNodeKey` prop to designate a property like your object’s ID to be used in the path. By default it uses the position in the tree, which has the drawbacks you explained here.
