### ISSUE TITLE
children order issue

### ISSUE THREAD

**Issue by Springbach** [fritz-c/react-sortable-tree#176]
For example, two children have same parent.
So we have 
///////////////////////////
ParentNode {
children:[ChildNode1,ChildNode2],
...
}
////////////////////////
Is there any way to render ChildNodes in order they placed in Parent node children array?

For now it renders the same. No matter the order in Parent node children array

(1)ParentNode {
children:[ChildNode1,ChildNode2],
...
}

or

(2)ParentNode {
children:[ChildNode2,ChildNode1],
...
}

=== renders

ParentNode
  - ChildNode1
  - ChildNode2

But I want to render in (2)situation tree like this: 
   ParentNode
      - ChildNode2
      - ChildNode1

**Comment by fritz-c** [comment]
They should be displayed in the order they’re given in the array. Could you perhaps provide a code sample demonstrating the unexpected behavior?

**Comment by Springbach** [comment]
Thank you very much for your answer. I have found a bug in my code. it was connected with getFlatDataFromTree function. Please close this issue.:-)
