### ISSUE TITLE
preventing some children from being parents

### ISSUE THREAD

**Issue by mikevandre** [fritz-c/react-sortable-tree#18]
Just evaluating this to see if it will work for my situation. Is there any way I can prevent some children from being parents? Also, can I supply metadata beyond title, subtitle, etc. Can I have different types of nodes that render differently?

**Comment by fritz-c** [comment]
#### 1. Prevent children from being parents
Of your three questions, this is probably the most difficult to implement. I recently looked into adding a `canDrop` method that the user can customize to prevent dropping under certain circumstances. However, the amount of calculation that goes into seeing where the node will land in the tree, repeated every time there's a new `drag` event over the drop area, makes it really difficult to provide a flexible _and_ performant `canDrop` API. I plan on revisiting that problem eventually, and am welcome to any suggestions for how to make it work quickly.

#### 2. Metadata beyond title, subtitle
Just add anything you want in the data for the nodes, and it will be available in every callback.

#### 3. Different types of nodes that render differently
If it's just style differences, you can use the `generateNodeProps` prop to add certain `className` props based on the node info.
If you want to more than that, you can set the `nodeContentRenderer` prop to a component you create yourself. With this, almost any aspect of the appearance of the nodes can be changed. If you decide to take this path, I highly recommend copying the `node-renderer-default.js` and `node-renderer-default.scss` files to your own code base and modifying them as you need.

Even if this library doesn't seem like a good choice for your project, you might consider using the functions in `tree-data-utils.js` to manipulate tree data.

**Comment by tonilaukka** [comment]
**1. Prevent children from being parents**
@mikevandre react-dnd uses types wich let you specify which drag sources and drop targets are compatible. [DropTarget](https://gaearon.github.io/react-dnd/docs-drop-target.html). Looked quickly through the code and seems like every dragsource is passed with default ItemTypes.HANDLE: https://github.com/fritz-c/react-sortable-tree/blob/3e8e10e276beeaf47aa99965e9a41a1cb05712a7/src/utils/drag-and-drop-utils.js#L214

Other than that @fritz-c has done an excellent job!  I've been working on similar project and `tree-data-utils.js` gave me some good ideas how to better flatten the tree.

**Comment by fritz-c** [comment]
I just released the `canDrop` API with version 0.1.13. I think this should help you do what you're trying to do.
