### ISSUE TITLE
Loading tree data from MySQL Database

### ISSUE THREAD

**Issue by edargham** [fritz-c/react-sortable-tree#182]
I want use the tree to render some data from my sql database, In what form should I place the rows in my array for it to properly render in the tree?

**Comment by fritz-c** [comment]
Check out the Data Import/Export example in the storybook and tell me if that answers your question. 
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=treeData%20import%2Fexport&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

**Comment by edargham** [comment]
Should my Table columns be of the same name as the initial data ones?

**Comment by fritz-c** [comment]
Use the `getKey` and `getParentKey` arguments to `getTreeFromFlatData` to specify how to access the columns for your row’s ID and the ID of its parent.

**Comment by edargham** [comment]
for some odd reasons, webpack fails to compile these lines

`ERROR in ./public/tree.js
Module build failed: SyntaxError: Unexpected token (31:47)

  29 |     this.state = {
  30 |         treeData: getTreeFromFlatData({
> 31 |           flatData: initialData.map(node => ({ ...node, title: node.name })),
     |                                                ^
  32 |           getKey: node => node.id, // resolve a node's key
  33 |           getParentKey: node => node.parent, // resolve a node's parent's key
  34 |           rootKey: null, // The value of the parent key when there is no parent (i.e., at root level)
`
Could it be that i need a different version of webpack to have it run properly?

**Comment by fritz-c** [comment]
Need to use this plugin with babel in order to support the `...` syntax for objects (e.g., `{...obj, a: 1}`):
https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread

**Comment by edargham** [comment]
Do I include the plugin in the webpack file, how is it used?

**Comment by fritz-c** [comment]
Check the README in that link I posted, under Installation and Usage.

**Comment by edargham** [comment]
Okay so I loaded the module, but now it's returning a typeError:
<img width="968" alt="screen shot 2017-10-23 at 1 40 39 pm" src="https://user-images.githubusercontent.com/29617612/31885340-df63a2bc-b7f8-11e7-9e93-a1aeebf15986.png">
I made sure webpack is up to date, since according to various threads it may be the cause of the problem. however it did not solve it in my case.

**Comment by fritz-c** [comment]
Can you post your `.babelrc` contents here?

**Comment by fritz-c** [comment]
And your webpack config as well, if possible.

**Comment by edargham** [comment]
**.babelrc**

[babelrc.txt](https://github.com/fritz-c/react-sortable-tree/files/1407241/babelrc.txt)

webpack.config.js

[webpack.config.txt](https://github.com/fritz-c/react-sortable-tree/files/1407243/webpack.config.txt)

**Comment by fritz-c** [comment]
Your `.babelrc` is good.

In your webpack config, remove the `babelPluginTransformObjectRestSpread` from the plugins array (as it's a plugin for babel and not webpack). You don't need to require it in that file either - everything should be handled by the .babelrc.
Also, delete the `query` portion under `babel-loader`, as that is also handled by the .babelrc

**Comment by edargham** [comment]
I'm sorry for returning this late:

I have a problem: I am Loading data from MySQL Database and pasting them in a treeview form however, I keep on getting this error mentioned in the title, and it logs in an infinite loop.

What I intend to do is load data from server in Load.js, pass them into Tree.js as props, and handle the rendering from there.

I am using react-sortable-tree package by fritz-c in order to build my tree.

Here's the code:

Load.js:
 
`
import React, { Component } from 'react';
import SortableTree, { addNodeUnderParent, removeNodeAtPath,  
getFlatDataFromTree,
getTreeFromFlatData, } from 'react-sortable-tree';
import Tree from './tree';

class Load extends Component{

constructor(props) {
    super(props);
    this.state = {
        dbData:[]
    };
}

loadSkillsFromServer() {
    $.ajax({
        url: '/api/skills',
        dataType: 'json',
        cache: false,
        success: function(data) {
            //set the state with the newly loaded data so the display will update
            this.setState({dbData: data});
        }.bind(this),
        error: function(xhr, status, err) {
            console.error('/api/skills', status, err.toString());
        }.bind(this)
    });
}

componentDidMount() {
    //Once the component is fully loaded, we grab the skills
    this.loadSkillsFromServer();
    //... and set an interval to continuously load new data:
    setInterval(this.loadSkillsFromServer, this.props.pollInterval);
}

render(){
    console.log(this.state.dbData);
    return (
        <Tree data = {this.state.dbData} />
    );
}

}



`

Tree.js:

`
import React, { Component } from 'react';
import SortableTree, { addNodeUnderParent, removeNodeAtPath,  
getFlatDataFromTree,
getTreeFromFlatData, } from 'react-sortable-tree';

export default class Tree extends Component {

constructor() {
super();
this.state = {
        treeData: getTreeFromFlatData({
          flatData: this.props.data.map(node => ({ ...node, title: 
          node.Skill_Name })),
          getKey: node => node.idSkill, // resolve a node's key
          getParentKey: node => node.Parent_Skill_ID, // resolve a 
          node's parent's key
          rootKey: null, // The value of the parent key when there is 
          no parent (i.e., at root level)
        }),
      };
   }

  render() {

  return (
     <div style={{ height: 1000 }}>
      <SortableTree
        treeData={this.state.treeData}
        onChange={treeData => this.setState({ treeData })}
      />
     </div>
  );
 }
}
`

**Comment by edargham** [comment]
Nevermind, I solved this problem. thanks for the help provided! :-) 👍

**Comment by NickEmpetvee** [comment]
@edargham How did you resolve the last issue?

**Comment by AmbushIV** [comment]
> @edargham How did you resolve the last issue?

I would like to know that too!
