### ISSUE TITLE
[Doubt] print absolute path to a node

### ISSUE THREAD

**Issue by arvind-simility** [fritz-c/react-sortable-tree#183]
Hi Fritz, 
   Firstly, very useful library! I have a doubt regarding printing the absolute path of a given node. For example, with the data set
{ title: 'A', children: [{ title: 'B', children: [{title: 'C'}] }] }

selecting C or searching for it should given me something like A->B->C rather than [0,1,2]. Is there a way to convert the path [0,1,2] to A->B->C ? I've gone through the documentation, I might be missing something. Please help me.

**Comment by fritz-c** [comment]
Use the `getNodeKey` prop. Just be sure that each value you set is unique within the tree.

**Comment by arvind-simility** [comment]
Great! That helps. Another doubt though, say we have a data set like the needle and haystack like this https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Search&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

Then how do will we get the paths?

**Comment by fritz-c** [comment]
You mean a bunch of unique items with names that might be duplicated? I think you would have to arbitrarily apply some unique ID to each item, and have an object containing all the ids as keys and names as values. With that, you can take a path constructed of ids and turn it into a path of names.

**Comment by arvind-simility** [comment]
Yes, that makes sense.. Thanks a lot :)
