### ISSUE TITLE
tree view does not render properly

### ISSUE THREAD

**Issue by spookyfox** [fritz-c/react-sortable-tree#184]
Hi,

I really like your tree view and use it heavily in projects. Usually I did use it for a desktop app running by node web kit and it works very well w/o any issue. For another project it is supposed to be running as web app, hence I transferred al lot of code to this project. While it works technically, there is an issue related to the rendering, see below yellow marked.

Do you have a clue what could be the issue?

Thanks in advance, for supporting; much appreciated.

![image](https://user-images.githubusercontent.com/14878872/32043892-4ac3b28c-ba3c-11e7-9b66-1e603bb8a5a0.png)

**Comment by fritz-c** [comment]
Hard to tell without a look inside the inspector. As the scaffolding pieces on the right are inline-block, I would suspect something like text-align screwing it up.

Check the css on the ancestor elements to make sure they don’t have anything applying float or margin on all their descendants.

**Comment by spookyfox** [comment]
Thanks for this idea...I looked through the App.css and your'e right there were some settings causing this issue. Now it works properly! Thx for your quick response as well!
