### ISSUE TITLE
Data not mapping properly when using Server Data

### ISSUE THREAD

**Issue by edargham** [fritz-c/react-sortable-tree#189]
I was able to load MySQL database rows into `initialData`, however, It doesn't seem to be mapped properly into `treeData`, to be rendered in the tree. I simple copy pasted the code found in `tree-data-io.js`, and added a function to load my rows into initialData. Should I use the same `id`,`name`,`parent` names like the ones in the original file? If not how can I solve this?

Here's the content of `initialData`:

<img width="1268" alt="screen shot 2017-11-02 at 8 32 48 am" src="https://user-images.githubusercontent.com/29617612/32313217-6d6a494a-bfaa-11e7-9974-022c17e6cc8d.png">

Here is my version of `tree-data-io.js`:

<img width="1077" alt="screen shot 2017-11-02 at 8 39 31 am" src="https://user-images.githubusercontent.com/29617612/32313232-83d8bf54-bfaa-11e7-86ac-c7d370808314.png">
<img width="1079" alt="screen shot 2017-11-02 at 8 40 06 am" src="https://user-images.githubusercontent.com/29617612/32313239-89779c78-bfaa-11e7-8386-3eb1bb7d483d.png">
<img width="1079" alt="screen shot 2017-11-02 at 8 41 01 am" src="https://user-images.githubusercontent.com/29617612/32313242-8e3b9868-bfaa-11e7-98e4-7e4ff569434e.png">

**Comment by edargham** [comment]
@fritz-c Please I still have the issue, and I do not know how to solve it.

**Comment by fritz-c** [comment]
Try setting the `rootKey` value in your call to `getTreeFromFlatData` to `0` instead of `null`.

**Comment by edargham** [comment]
Yeah it worked! thank you very much for the help :-)
