### ISSUE TITLE
I have a puzzle about dragging and dropping nodes to a specific area

### ISSUE THREAD

**Issue by linmodev** [fritz-c/react-sortable-tree#191]
* Please look at my example.
* https://codesandbox.io/s/ywlkpqnmnj

On my example, `O`  `C` `J` all is directory. `A` `B` `N` all is file. Directory has children. File has no children, so return true or false by canDrop API callback function parameter nextParent.children.
* First 
 When I print nextParent, I found nextParent children have two same nodes in children field.

* Second
 If I drag `N` node to above `A` node and can't to `O` `C` `J` node, because `O` `C` `J` node all is directory. I mean the file node will be drag and drop location, not only the parent node is the directory node, the sibling node can only be a file node. Directory nodes will be drag and drop location, not only the parent node is a directory node, sibling nodes can only be directory nodes.

What should I do? I think canDrop callback function should provide sibling node information.

**Comment by linmodev** [comment]
The first problem maybe a bug, but I can add some field to my treeData finish my work.
But the second i need your help. Thank you very much for the development of this component, it has played a crucial role in our business

**Comment by lifejuggler** [comment]
@linmodev, your codesandbox is broken

**Comment by linmodev** [comment]
@lifejuggler ,is it working now?

**Comment by lifejuggler** [comment]
I am getting an error in the console box along with this, what is it supposed to look like?
![screen shot 2017-11-14 at 3 26 08 pm](https://user-images.githubusercontent.com/3578716/32803063-5765eadc-c950-11e7-99f8-f846981ca422.png)

**Comment by linmodev** [comment]
![image](https://user-images.githubusercontent.com/21982105/32821719-d89ce99c-ca0f-11e7-9785-6faaa27102d9.png)
I don't get any error. what happened？

**Comment by lifejuggler** [comment]
Not sure.. maybe you didn't save your change?

**Comment by fritz-c** [comment]
What I gathered from your explanation is that in a given level, you want to keep directories at the top, and files at the bottom. You're correct about there being no good way to handle `canDrop` based on siblings with the current API. It's a bit of a workaround, but something you can do is ensure the order by rearranging whenever the drop occurs (i.e., in `onChange`). I've implemented an example based on your example here: https://codesandbox.io/s/mkov7oy58

**Comment by linmodev** [comment]
@fritz-c  @lifejuggler Thank you very much for your help, I am already using a method similar to you to achieve my goal. I found this sandbox seems to be a problem in different networks, in any case, my problem has been initially solved.
