### ISSUE TITLE
How to duplicate/clone nodes?

### ISSUE THREAD

**Issue by borisyordanov** [fritz-c/react-sortable-tree#196]
Can anyone recommend what the best way to implement a button that when clicked clones a node in the current level of the tree?

Before clicking the button
![image](https://user-images.githubusercontent.com/12392666/32894018-d0b5b480-cadb-11e7-9049-af1ec4bcd8fc.png)

After clicking the button
![image](https://user-images.githubusercontent.com/12392666/32894045-e6beb736-cadb-11e7-93f5-16a58f430937.png)

**Comment by borisyordanov** [comment]
After a bit more fiddling i think i can answer the question, but i'd still appreciate feedback.

If this is the setup you are using for the "Add Child" button:

`<button
                  onClick={() =>
                    this.setState(state => ({
                      treeData: addNodeUnderParent({
                        treeData: state.treeData,
                        parentKey: path[path.length - 1],
                        expandParent: true,
                        getNodeKey,
                        newNode: {
                          title: `${getRandomName()} ${node.title.split(
                            " "
                          )[0]}`
                        }
                      }).treeData
                    }))}
                >
                  Add Child
                </button>`

the only thing you need to modify is the `parentKey` value. If you set it to `parentKey: path[path.length - 2]` it will function in the manner i explained in my original question.

Here is the full code for a button that clones nodes:
` <button
                  onClick={() =>
                    this.setState(state => ({
                      treeData: addNodeUnderParent({
                        treeData: state.treeData,
                        parentKey: path[path.length - 2],
                        expandParent: true,
                        getNodeKey,
                        newNode: {
                          title: `${getRandomName()} ${node.title.split(
                            " "
                          )[0]}`
                        }
                      }).treeData
                    }))}
                >
                  Clone
                </button>`

**Comment by lifejuggler** [comment]
just create a custom function that is bound to the clone button that just inserts the node into the treeData

**Comment by fritz-c** [comment]
Use either `changeNodeAtPath` or `addNodeUnderParent`, combined with the `path` (subtracting the last entry to get the parent path) value you’re given by the prop mapping api.

**Comment by borisyordanov** [comment]
@fritz-c I'm not 100% sure i understood what you mean, but this is how i ended up solving it (with addNodeUnderParent):

    <button
        onClick={() =>
        {
            this.setState(state => ({
            treeData: addNodeUnderParent({
            treeData: state.treeData,
            parentKey: path[path.length - 2], //the "-2" adds the new node as a sibling, if it was "-1" it will add it as a child
            expandParent: true,
            getNodeKey,
            newNode: {
                title: node.title, //the new node's title should be the same as the clicked one
                subtitle: node.subtitle //the new node's subtitle should be the same as the clicked one
            }
            }).treeData
        }))}}
    >Clone</button>

**Comment by mariovde** [comment]
@borisyordanov thanks for the code!
The behavior I get with your code, is that it doesn't copy the child nodes of the node from which you click "clone". 
Is there a way you think, to include all the subnodes as well?

**Comment by borisyordanov** [comment]
@mariovde I haven't used this library in a while. I think there was a way to include all the subnodes, but not sure what it is any more
