### ISSUE TITLE
How to add more labels to nodes?

### ISSUE THREAD

**Issue by borisyordanov** [fritz-c/react-sortable-tree#197]
We know each node has the following properties:

`title` is the primary label for the node.
`subtitle` is a secondary label for the node.
`expanded` shows children of the node if true, or hides them if false. Defaults to false.
`children` is an array of child nodes belonging to the node.

But what if you want to attach more data to a node and display it in the tree? Can you add more labels to nodes? What is the best solution?

FYI an obvious quick and dirty solution would be to concatenate the data and store it in the two labels provided in the 

Example:
```
{ 
    title: 'value1', 
    sub-title: 'value2', 
    id: 'value3' //this is an extra addition
    history: [], //this is an extra addition
    expanded: true, 
    children: []
}
```

**Comment by fritz-c** [comment]
Something like this would work:
https://codesandbox.io/s/l92xx8wxp9

**Comment by borisyordanov** [comment]
I came up with a similar solution myself. Thanks!
