### ISSUE TITLE
Include node info in rowHeight callback

### ISSUE THREAD

**Issue by fritz-c** [fritz-c/react-sortable-tree#199]

**Comment by lifejuggler** [comment]
@fritz-c I will make a pull request

**Comment by lifejuggler** [comment]
@fritz-c actually I don't understand this enhancement, why do you need to include node info into the rowheight callback?

**Comment by lifejuggler** [comment]
@fritz-c actually can you give me more context to this issue?

**Comment by C3PablO** [comment]
Is there any way to go around this? to have different heights based based on node data?

**Comment by fritz-c** [comment]
@C3PablO Not right now. Would you be interested in adding the functionality? I believe it's only a matter of plugging in some extra variables into the callback call.

**Comment by C3PablO** [comment]
yes, I think that would very useful. For what I've seen around the issues, there was a fix for this in 1.3.0 ([a906f21](https://github.com/fritz-c/react-sortable-tree/pull/158)). No sure where that went. Another solution I'm looking at is the possibility of wrapping the cell into a [CellMeasurer](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md) for rows where the height is difficult to guess so the node height is set based on the content. Think of a list of comments.

**Comment by fritz-c** [comment]
That fix you refer to only applied to non-virtualized trees. For whatever reason I didn't notice the virtualized version didn't get any attention.

**Comment by wuweiweiwu** [comment]
@fritz-c if its not done already i can do it :)

**Comment by fritz-c** [comment]
@wuweiweiwu yes please!

**Comment by wuweiweiwu** [comment]
#231 pull request submitted!

**Comment by fritz-c** [comment]
Available now in `v1.6.0`. Thanks for the help!
