### ISSUE TITLE
Docs Improvment: Requires mangling in uglifyjs to be false

### ISSUE THREAD

**Issue by sazo** [fritz-c/react-sortable-tree#202]
Can we improve the docs to include its importen to disable mangling in uglifyJS - if you are using this plugin. :)

I have spend a pretty amount of hours figuring this out.

**Comment by fritz-c** [comment]
I took uglifyjs out of the build process for the latest version. Can you tell me if this is still an issue?

**Comment by fritz-c** [comment]
I'm putting UglifyJS back into the build as its absence is causing issues with other users. I think adding `comparisons: false` to your UglifyJS config, as seen here
https://github.com/facebookincubator/create-react-app/pull/2379/files
works as a temporary workaround.
