### ISSUE TITLE
Dragging without using the drag handle

### ISSUE THREAD

**Issue by borisyordanov** [fritz-c/react-sortable-tree#204]
I saw that in the [file explorer theme](https://github.com/fritz-c/react-sortable-tree-theme-file-explorer) the drag handles have been omitted and now just dragging the item itself works.

How can i remove this part (the one in the image below) of each node and allow dragging by clicking anywhere on a node (while still using the default theme)?
![image](https://user-images.githubusercontent.com/12392666/33265595-90c607a4-d372-11e7-9588-e7d72d289445.png)

**Comment by fritz-c** [comment]
That would require a custom theme. If you decide to make one, please share it here, and I can add it to the list in the readme.

**Comment by borisyordanov** [comment]
@fritz-c That works for me. I'd definitely need to make a custom theme. If you can point me in the right direction how to go about that - it'd go a long way.

**Comment by fritz-c** [comment]
I figured it was a common enough use case that I created the theme myself: [react-sortable-tree-theme-full-node-drag](https://github.com/fritz-c/react-sortable-tree-theme-full-node-drag)

**Comment by borisyordanov** [comment]
@fritz-c Wow that's great! I'll still need to modify it a bit, because i want to reduce the height and spacing of the nodes, to reduce the vertical size of the tree, but your theme will definitely help me get there. Thanks for taking the time to make it!

**Comment by borisyordanov** [comment]
@fritz-c I tried out the new theme, wasn't sure if i should post a new issue and whether it should be in this repo, or the theme's repo, but i'm getting these errors after i installed it:
![image](https://user-images.githubusercontent.com/12392666/33525081-4dab54f0-d828-11e7-9940-5bc2cf3a71eb.png)

**Comment by fritz-c** [comment]
@borisyordanov I’ll investigate it as soon as I get the chance. Just to be sure - are you on the latest version of react-sortable-tree?

**Comment by borisyordanov** [comment]
@fritz-c The errors are defiently from the new theme because if i comment out `theme={DragAndDropExplorerTheme}` they don't show up in the console anymore. Here's a snippet of my packages.json:
```
  "dependencies": {
    "autosuggest-highlight": "^3.1.1",
    "eslint-config-airbnb": "^16.1.0",
    "firebase": "^4.6.2",
    "firebase-auto-ids": "^1.1.0",
    "material-ui": "^0.19.4",
    "material-ui-icons": "^1.0.0-beta.17",
    "re-base": "^3.2.0",
    "react": "^16.1.1",
    "react-autosuggest": "^9.3.2",
    "react-dom": "^16.1.1",
    "react-scripts": "1.0.17",
    "react-sortable-tree": "^1.5.0",
    "react-sortable-tree-theme-file-explorer": "^1.1.2",
    "react-sortable-tree-theme-full-node-drag": "^1.1.0",
    "reactfire": "^1.0.0",
    "typeface-roboto": "0.0.45"
  }
```
