### ISSUE TITLE
suggestion: keep basic template simple

### ISSUE THREAD

**Issue by lifejuggler** [fritz-c/react-sortable-tree#205]
the current default template seems alittle too customized for a default theme... why not have that be a specific theme that people can designate and maybe simply the default theme to be alittle more minimalistic and basic? (possible design idea: https://examples.sencha.com/extjs/6.2.0/examples/kitchensink/#basic-trees)

**Comment by fritz-c** [comment]
True. It would be a breaking change, but I agree with your logic.

I kind of like the presence of the drag handle, as it’s a common UI to indicate the ability to drag. If you’re suggesting a plainer, full-width style, I’d like to figure out a way that the draggability can be understood easily.

**Comment by buzztone** [comment]
> I kind of like the presence of the drag handle, as it’s a common UI to indicate the ability to drag.

In our user testing (not extensive at this stage) some Desktop users have found the drag handle confusing (actually they did know that clicking there let you drag the node). They did not associate the 'hamburger' icon with the ability to the drag the node.

> If you’re suggesting a plainer, full-width style, I’d like to figure out a way that the draggability can be understood easily.

In our application (creating web forms) we would love to see a full-width style option which still highlighted the draggability.

**Comment by zourbuth** [comment]
+1

**Comment by JWaldenback** [comment]
This is my suggestion to the discussion. 

If the original theme is more compact it will most likely be suited in more user cases. Look at the two pictures below. The right one is more compact and displays the same information as the left one in almost half the space.
![image](https://user-images.githubusercontent.com/19432538/32365076-99c33b90-c078-11e7-8eb1-786963d70bd8.png)

**Comment by lifejuggler** [comment]
sizing could be an issue but I feel that it is merely a side product of the current design issue. @fritz-c I will come up with a rough prototype and put it up as a theme and if people find that to be better default maybe we can swap it. I have a few ideas in making it a bit easier to comprehend that it is a draggable node without having a designated space just to enable a drag function

**Comment by lifejuggler** [comment]
Hello, been pretty busy and was able to get this out now.... @fritz-c, @JWaldenback, @buzztone, Would you guys be able to give me some feedback on this?

**Comment by fritz-c** [comment]
Can you provide a link, and maybe a demo site?

**Comment by JWaldenback** [comment]
@lifejuggler How do I find your solution? I'm interested in seeing what you've accomplished.

**Comment by lifejuggler** [comment]
@JWaldenback , @fritz-c sorry for getting this so late... I had heck of a time at work... https://minimal-sortabletree-theme.herokuapp.com/

**Comment by lifejuggler** [comment]
Any thoughts about my new basic theme proposal and the example that I provided? @JWaldenback, @fritz-c?

**Comment by JWaldenback** [comment]
@lifejuggler I like it. But I would it to be more compact. Is that easily changed?

Have you seen this full node drag theme that fritz-c has made btw? I like it a lot, though it also needs to be more compact imo. Or at least easily customizable to change the height and size of the nodes.
https://github.com/fritz-c/react-sortable-tree-theme-full-node-drag

**Comment by wuweiweiwu** [comment]
@lifejuggler @JWaldenback Feel free to make a PR :)

**Comment by lifejuggler** [comment]
@JWaldenback, height should be adjustable... let me know if it isn't

**Comment by lifejuggler** [comment]
@fritz-c , @wuweiweiwu, I made a pull request with the new custom theme added into the readme

**Comment by wuweiweiwu** [comment]
closed by #289
