### ISSUE TITLE
Feature: `onDragStateChanged` callback

### ISSUE THREAD

**Issue by fritz-c** [fritz-c/react-sortable-tree#207]
Make a prop called `onDragStateChanged`, to track switching between the following states:
- dropped
- dragging

And if dragging, whether it can be dropped or not.

Based on a comment here: https://github.com/fritz-c/react-sortable-tree/issues/167#issuecomment-347073595

**Comment by wuweiweiwu** [comment]
@fritz-c I can look into this as well

**Comment by fritz-c** [comment]
Available now in v1.7.0
