### ISSUE TITLE
Context menu?

### ISSUE THREAD

**Issue by rogerjak** [fritz-c/react-sortable-tree#212]
Anyone knows a context menu that works with RST?
I've tried both react-contexify and react-contextmenu but none of them works as expected.

Thanks

**Comment by borisyordanov** [comment]
@rogerjak What exactly is wrong with the context menu libs you mentioned? Can you show us a demo?

**Comment by rogerjak** [comment]
I got it working with react-contextmenu, by wrapping the title with ContextMenuTrigger in generateNodeProps. Guess I have to use customNodeRenderer to be able to wrap the whole node?

**Comment by borisyordanov** [comment]
@rogerjak you probably meant `nodeContentRenderer` not `customNodeRenderer` and yes - it looks like it. Why are you not able to wrap the whole the whole node with the way you are using it now? You can put multiple components in a title (or subtitle or whatever) and therefore the title will be you whole node.

Here's an example:

```
 title: (
	<div>
	  <NodePrefix prefix={node.prefix} />
	  <Autosuggest suggestions={this.props.state.suggestions} />
	  <NodeNumber number={node.number} />
	</div>
  )
```

**Comment by rogerjak** [comment]
I was using the provided icon prop, but you're right, I can move the icon into the title and wrap it. Thanks!

**Comment by Amitdevelopment** [comment]
I have used this context menu and it is working fine.
https://github.com/vkbansal/react-contextmenu

**Comment by wuweiweiwu** [comment]
I am going to close this. Seems to be resolved.
