### ISSUE TITLE
onChange does not trigger if the change is programmatical

### ISSUE THREAD

**Issue by borisyordanov** [fritz-c/react-sortable-tree#216]
I added a console log, in the onChange prop of the SortableTree component -
 https://codesandbox.io/s/6w1zq7lk1k 

It seems onChange does not trigger if you apply changes to the tree by modifying the state - like when clicking the Add and Remove buttons. It is triggered if you, for example, drag one node to a new location. 

How can we listen for all change events?

**Comment by jzoric** [comment]
Hi,
I have a question: If you already change the tree data by setting the state why do you need `onChange` to be called again?

**Comment by borisyordanov** [comment]
Various parts of the app change the data. I want to capture all of them to implement a history/undo/redo. Right now I'm doing by using reacts lifecycle events and checking if the treeData has changed on every defender. 

Far from the best solution :)

**Comment by jzoric** [comment]
Understood. 
Idea: maybe you can turn off the `onChange` function and control treeData state from other various parts. You could use `onMoveNode` to capture the move event.

**Comment by borisyordanov** [comment]
Can you elaborate on that?

**Comment by jzoric** [comment]
` <SortableTree treeData={treeData}  onChange={() => {}} onMoveNode={this.onMoveNode} ..../>`
* `onChange` does nothing
* Implement `onMoveNode` which will update the state with the changed treeData
* By using button on node (like in your codesandbox example), every click will give you access to node so you can use it and update the state again with the changed treeData

If you have e.g redux in your app you can call an action for everything you do inside the app and that action can set the treeData state.

**Comment by borisyordanov** [comment]
Thanks @jzoric i'll give that a try.

**Comment by jzoric** [comment]
@borisyordanov hi, what is the status with this?

**Comment by borisyordanov** [comment]
@jzoric I looked into what you suggested a bit more and unfortunately it wasn't very helpful. Perhaps i wasn't clear in my previous posts. I'm not interested in capturing node move events. I want to capture ALL events.

My original problem was that if i change the treeData array, by using setState, for example, the onChange event is not triggered, event though react re-renders the page and displays the change. An event happens, it affects the tree structure, but i have no way of capturing it.

Upon further reading though i can't think of a way to implement a solution to this and it's not exactly the expected behaviour of the onChange event (the onChange in input elements, for example, is triggered only on browser events, and is also not triggered if you use setState). Therefore i don't think it's fair to keep this open as a bug, but can perhaps be regarded as a possible new feature.

**Comment by Punith13** [comment]
Hi @borisyordanov , 

I too faced similar issue, then used the useEffect hook to listen to treeData changes and perform post change work.
