### ISSUE TITLE
Support Multiple SortableTrees on one Page

### ISSUE THREAD

**Issue by ncphillips** [fritz-c/react-sortable-tree#22]
Current implementation does not elegantly handle multiple SortableTrees to be on the same page.

Dragging an item from one list to another causes serious problems, by deleting items in the other tree.

We need to be able to name the SortableTree. That name should be added to the drag type, to prevent items from one tree being dragged to other trees.

![sortabletreebug](https://cloud.githubusercontent.com/assets/824015/20628633/7df701dc-b2fd-11e6-94d0-6031d263c330.gif)

**Comment by ncphillips** [comment]
I'm working on fix for this.

**Comment by fritz-c** [comment]
The fix is now available in v0.1.6.
Thanks for bringing this to my attention!

**Comment by ncphillips** [comment]
Thanks for merging it @fritz-c! 

And again, I had to move things around a bit and I bad because I wasn't really sure how you would want that done.
