### ISSUE TITLE
Remove hard coded label

### ISSUE THREAD

**Issue by Vladimirtishenko** [fritz-c/react-sortable-tree#221]
Hi, please, make hard coded 'title' and 'subtitle' changeable

For example:
```
<SortableTree
     title="label"
     subtitle="url"
     treeData={this.props.menu}
     onChange={ treeData => this.props.changeTree(treeData) }
/>
```
If this field are not fill used default params  title="title", subtitle: "subtitle".

This will be more customized, since sometimes other fields are used coherently in the whole product and when using your module in the system, changes that are not standardized will be made. For example, we everywhere use a label instead of a title.

Of course, I can make a copy myself and fill it with npm, but I do not think this is necessary since there is already a ready-made module that is being developed and this small innovation will be pleasant for many developers.

Or maybe i can make merge request?

**Comment by borisyordanov** [comment]
I'm not sure i understood what you are trying to do. If you want the title (or subtitle) to be editable you should check out [this example](https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Modify%20nodes&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel).

You should try out the other examples and read up on the `generateNodeProps` prop

**Comment by Vladimirtishenko** [comment]
No sorry. I want to 'title' and 'subtitle' can be changed. The name itself

For examle: 

My state: {label: 'Hello', url: 'https://lol.com'}

<SortableTree
     title="label"
     subtitle="url"
     treeData={this.props.menu}
     onChange={ treeData => this.props.changeTree(treeData) }
/>

**Comment by Vladimirtishenko** [comment]
I want to use a 'lable' and 'url' and that it is displayed on the tree instead of title and subtitle

**Comment by borisyordanov** [comment]
I see - you want to rename the props on the component. In that case suggest forking the repo and making your own version, because title and subtitle are more ubiquitous than the ones you suggested. Perhaps the props names can be improved, but i don't think "label" and "url" are the best options. @fritz-c should add his input here.

**Comment by fritz-c** [comment]
Yeah, I think the current approach provides enough ways for the user to set their title/subtitle parts. If you want to avoid adding an extra property to your nodes just to remove it on export, I would recommend setting the title and subtitle via `generateNodeProps`, as @borisyordanov suggested.

**Comment by Vladimirtishenko** [comment]
I propose that 'title' and 'subtitle' were not mandatory and they could be changed. If they are specified as parameters ' title="label" ' then you need to use for the tree just 'label'' as the title text description,  and if not, use names appropriately 'title'. This will be a more custom solution. If you already have the opportunity to change them, can you give an example?

**Comment by cmmartin** [comment]
Use `generateNodeProps`. For example, to use `label` as the title and `url` as the subtitle

```javascript
<SortableTree
     generateNodeProps={({ node }) => ({ title: node.label, subtitle: node.url })}
/>

```

**Comment by Vladimirtishenko** [comment]
Thank you/
