### ISSUE TITLE
Moving nodes through data helper function

### ISSUE THREAD

**Issue by onyx1337** [fritz-c/react-sortable-tree#236]
Hi , 
Is there any way to change node path through data helper function ( without using dnd ) ?

**Comment by fritz-c** [comment]
Use removeNode to first get the target node and the treeData with your target node removed, and then call addNodeUnderParent to get the treeData with your node inserted back into the tree at the place you desire.

**Comment by onyx1337** [comment]
oh, that simple, thank you a lot @fritz-c
