### ISSUE TITLE
Rendering a form with generateNodeProps and addNodeUnderParent

### ISSUE THREAD

**Issue by edargham** [fritz-c/react-sortable-tree#238]
Just need a brief clarification, in order to add node under a parent, and have it bring up a form to prompt the user for input I must:

1.   `generateNodeProps` prop with a button that adds a child just like in `addNodeUnderParent`.
2.    To render the form, I must invoke the render function of the form inside the button.
3.    Data submitted to the form will be fed to the next lines (similar to the Add/Remove nodes 
       example in the storybook.).
4.    Also update the flat data accordingly.

Am I right?

**Comment by fritz-c** [comment]
Are you talking about a form inside a modal that pops up? If it's something like that, the button would only enable a state on your parent component, like `{ showForm: true, formTarget: "<parent node key>"}` and upon submission of the form it would add the node via `addNodeUnderParent`.

**Comment by edargham** [comment]
I was thinking of rendering the form directly as a child, it don't think it is very feasible, I'll do it as you suggest.

**Comment by edargham** [comment]
Alright, I built my modal via `react-bootstrap`, I linked it to the tree through a button. The modal would appear in the DOM, and the page will behave as if the modal is rendered however, the modal does not appear.

Here is the code to both the modal and the tree:

Modal:
<img width="706" alt="screen shot 2018-02-05 at 12 59 44 pm" src="https://user-images.githubusercontent.com/29617612/35801336-a55c7d90-0a74-11e8-9b05-6a0fb54b6742.png">
<img width="758" alt="screen shot 2018-02-05 at 12 59 59 pm" src="https://user-images.githubusercontent.com/29617612/35801337-a66e7116-0a74-11e8-8d44-73bf92945e05.png">

Tree:

<img width="646" alt="screen shot 2018-02-05 at 1 00 18 pm" src="https://user-images.githubusercontent.com/29617612/35801345-aef484ba-0a74-11e8-9a28-9d095b2475fb.png">
<img width="580" alt="screen shot 2018-02-05 at 1 00 33 pm" src="https://user-images.githubusercontent.com/29617612/35801346-b060ff86-0a74-11e8-8dcb-4aef19cb8117.png">

Snapshot of the page (Open in Safari):
Clearly the modal is in the DOM but not displaying well on the page:
<img width="1278" alt="screen shot 2018-02-05 at 1 03 17 pm" src="https://user-images.githubusercontent.com/29617612/35801455-29aa3a38-0a75-11e8-84e1-686a93c80683.png">
<img width="1280" alt="screen shot 2018-02-05 at 1 04 00 pm" src="https://user-images.githubusercontent.com/29617612/35801458-2b7a7b20-0a75-11e8-8e49-fe88942f5601.png">

Is it due to an issue in the tree, or just bad css styling from my end?

**Comment by fritz-c** [comment]
Seems like a styling issue. The only other thing I might guess is that the way you get the ref to the modal is outdated.

**Comment by edargham** [comment]
It is a styling issue, I removed the bootstrap.css file from the HTML page and the modal div appeared. I'll see how I can resolve it, Thanks for the help!
