### ISSUE TITLE
Drag & dropping of items does not work with Chromium

### ISSUE THREAD

**Issue by tuomas2** [fritz-c/react-sortable-tree#24]
Tested with Chromium version 53.0.2785.143 (From ubuntu 16.04).
Tested also with Chrome and Firefox on the same computer and works there OK.
![selection_047](https://cloud.githubusercontent.com/assets/5811789/20667253/ff8d8dc2-b570-11e6-95b1-2f43c0e087a1.png)

**Comment by fritz-c** [comment]
Can you try it once more with the latest version? The [demo](https://fritz-c.github.io/react-sortable-tree/) has been updated as well. 

I recently changed how scroll-on-drag works, and some of the bizarre stuff I had been doing might have been interfering.

**Comment by fritz-c** [comment]
Doing a bit of issue cleanup. Let me know if anything's changed.

**Comment by tuomas2** [comment]
Fix seems to work. Tested demo again.
