### ISSUE TITLE
Using SortableTreeWithoutDndContext, cannot read property 'getMonitor' of undefined

### ISSUE THREAD

**Issue by CASandmann** [fritz-c/react-sortable-tree#240]
I encountered an issue where I'm using React-DnD in another component in my codebase and never had to use both this and React-Sortable-Tree at the same time.  Now we have an instance where we want to, but when I switch `import SortableTree` to `import { SortableTreeWithoutDndContext as SortableTree }`, I get the error

    Cannot read property 'getMonitor' of undefined

It looks like it's trying to set `this.clearMonitorSubscription` in the `ComponentWillMount`.  Why am I getting this error?

**Comment by fritz-c** [comment]
Could it be that the SortableTree isn't a descendant of a component that had `DragDropContext` called on it? See this example for a working example:

https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Drag%20from%20external%20source&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel

Source: https://github.com/fritz-c/react-sortable-tree/blob/97610d1705451e260e4d1f2d587c169709f5a5de/examples/storybooks/external-node.js

**Comment by CASandmann** [comment]
Yes!  That was the problem.  This should probably be detailed in the [If it doesn't work with other components that use react-dnd](https://github.com/fritz-c/react-sortable-tree#if-it-doesnt-work-with-other-components-that-use-react-dnd) section of the Readme because as written, it implies that you don't need to wrap it since you didn't before.

**Comment by LucitheR** [comment]
@fritz-c  When you play with said Example (https://github.com/frontend-collective/react-sortable-tree/blob/97610d1705451e260e4d1f2d587c169709f5a5de/examples/storybooks/external-node.js) in CodeSandbox you get the same Error.

**Comment by vipinpatil** [comment]
@CASandmann  @fritz-c i have resolved this issue by replacing this line 
"react-sortable-tree": "1.5.0" in package.json file and install npm module again.

:) its resolved issues
