### ISSUE TITLE
package error in v1.8.1

### ISSUE THREAD

**Issue by owcc** [fritz-c/react-sortable-tree#243]
I just use RST v1.8.1, got this error
```
./node_modules/react-sortable-tree/node_modules/react-virtualized/dist/es/List/List.js
281:117-150 '../Grid' does not contain an export named 'bpfrpt_proptype_NoContentRenderer'
```
**update!**
it looks like `react-virtualized`v9.18.1 failed, [9.18.1 Kills build!](https://github.com/bvaughn/react-virtualized/issues/989)
how can I use `react-virtualized` module in my project other than module in `react-sortable-tree` itself?

**Comment by TrySound** [comment]
Fixed in react-virtualized 9.18.2
