### ISSUE TITLE
Variable Height Nodes

### ISSUE THREAD

**Issue by mhiggs** [fritz-c/react-sortable-tree#244]
First off, this is an awesome project, thanks for sharing it!

We have been using your tree to implement a feature that, at times, will have a lot of text in some nodes and very little text in others.  The hope was to allow word-wrap in each node and everything would be well and good. However after digging around I realized that rowHeight is global for all nodes, and seems to be used to position the nodes in the correct place.

Is there a way to have variable height set at each node to adjust to the content? 

Thanks!

**Comment by mhiggs** [comment]
For future people who need something similar we were able to achieve this through unsetting styling in custom node css to allow for relative positioning, which solved for our use case.

```
.rstcustom__node {
    height: unset !important;
    position: relative !important;
    top: unset !important;
}
```

**Comment by mjyoung** [comment]
@mhiggs Were you able to get word wrapping working for the node titles? Can you explain how you implemented the `.rstcustom__node` snippet above?

**Comment by akhilesh-94** [comment]
Was this achieved?

**Comment by d9k** [comment]
`rowHeight` can now be callback but there are issues with that: #264
