### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by mbrowne** [fritz-c/react-sortable-tree#248]
FYI, the link to react-sortable-tree-theme-full-node-drag in the readme is broken. It is currently pointing to:
https://www.npmjs.com/package/react-sortable-tree-full-node-drag

It should instead point to:
https://www.npmjs.com/package/react-sortable-tree-theme-full-node-drag

Cheers,
Matt

**Comment by fritz-c** [comment]
Thanks!
