### ISSUE TITLE
Incorrect paths when moving nodes

### ISSUE THREAD

**Issue by ryanmeisters** [fritz-c/react-sortable-tree#255]
Perhaps I am misunderstanding the path parameters of `onMoveNode` (`path`, `prevPath`, `nextPath`), but they seem to behave oddly. I would expect each array of children to be 0-indexed, but this doesn't seem to be the case.

For example, I modified [this sandbox](https://codesandbox.io/s/7kxvk8nk3j) to console.log the paths when a node is moved. 

Moving N2 to first child of N1:
expected `prevPath`: [1]
expected `nextPath`: [0, 0]
actual `prevPath`: [1]
actual `nextPath`: [0, 1]

Moving N1 to first child of N4: 
expected `prevPath`: [0]
expected `nextPath`: [0, 0, 0, 0]
actual `prevPath`: [0]
actual `nextPath`: [0, 1, 2, 3]

It seems like children are n-indexed, where n is the tree depth. Is this expected?

**Comment by fritz-c** [comment]
When you don’t set your own “node key” with `getNodeKey`, the path elements point to the index of the node within the visible part of the tree.

**Comment by ryanmeisters** [comment]
ah I see, I thought Was implementing getNodeKey, but wasn't. Thanks for the quick response and thanks for a great lib!
