### ISSUE TITLE
onDragStateChanged is not working .

### ISSUE THREAD

**Issue by amttmr** [fritz-c/react-sortable-tree#258]
# Reporting a Bug?

I am not sure what i am doing wrong. But onDragStateChanged() function is not being called when a node drag is initiated.

### here is my function : 
```
_onDragStateChanged = ({isDragging,draggedNode}: {isDragging: boolean, draggedNode: Item}) => {
    console.log(isDragging)
    console.log(draggedNode)
  }
```

### here is my component: 
```
<SortableTree
            treeData={tree}
            onChange={treeData => this.props.updateData(treeData)}
            theme={FileExplorerTheme}
            generateNodeProps={this._generateNodeProps}
            onMoveNode={this._onMoveNode}
            getNodeKey={getNodeKey}
            onVisibilityToggle={this._handleVisibilityToggle}
            canDrag={this._canDrag}
            canDrop={this._canDrop}
            onDragStateChanged={this._onDragStateChanged}
          />
```

**Comment by fritz-c** [comment]
Can you fork the codesandbox example linked in the readme and create a minimal reproduction of this bug?

**Comment by amttmr** [comment]
Thanks! But i found a workaround to achieve the desired output. No longer using this  onDragStateChanged function.

**Comment by charue808** [comment]
Hi, I am also getting this issue. I implemented it as done in the storybook example onVisibilityToggle and onMovdeNode work but noDragStateChanged doesn't. I'm not sure if onDragStateChanged is needed for my project, or how it could improve it,  but i haven't gotten it to work. Thanks for this project though it's really awesome.

**Comment by charue808** [comment]
Nevermind, i needed to update the version that I was using. still not quite sure how to use it but it works now.
