### ISSUE TITLE
Can i change the style ?

### ISSUE THREAD

**Issue by Suremotoo** [fritz-c/react-sortable-tree#284]
it's landscape orientation  , example:

![demo](https://user-images.githubusercontent.com/26423989/38490639-323cc16a-3c1c-11e8-8e0d-a4cf83d18612.jpg)

**Comment by wuweiweiwu** [comment]
You can do custom styling on the nodes using `generateNodeProps` or use a theme :) Hope that helps

**Comment by Suremotoo** [comment]
i'm so sorry, The doc it's simple, can you offer me a demo?  thanks.

**Comment by wuweiweiwu** [comment]
@Suremotoo feel free to reopen if you have more questions
