### ISSUE TITLE
Custom sort order when saving tree to database

### ISSUE THREAD

**Issue by neurobutter** [fritz-c/react-sortable-tree#287]
First of all, thank you so much for this wonderful project.

I am trying to save my tree to a relational database. Can I manually set the sort order using "treeindex"? I'm currently using the import getTreeFromFlatData utils. I want to be able to save custom sort order of the tree to DB... is this possible? 

eg. data looks like this: 

const initialData = [
  { id: '1', name: 'N1', parent: null, treeIndex: 0 },
  { id: '2', name: 'N2', parent: null, treeIndex: 1 },
  { id: '3', name: 'N3', parent: 2, treeIndex: 2 },
  { id: '4', name: 'N4', parent: 3, treeIndex: 3},
];

I know that by moving the nodes around I would have to re-save the new treeIndexes that were moved around. Any help or advice on how the library can help me achieve this would be appreciated!

**Comment by neurobutter** [comment]
In case it's not clear: 

I have no problem saving the treeIndex to the database to retain sort order, but when reading the nodes from the db, i have no idea how to set the treeIndex property directly in the sortable tree control - or whether it's even possible. My index is also saved in the DB as tree_index, not sure how to alias it as "treeIndex" on the way back, using the import utils.

**Comment by wuweiweiwu** [comment]
is there something preventing you from saving it to the db as `treeIndex` or simply adding another field on in the returned JSON ?

**Comment by neurobutter** [comment]
Thanks for your response. I think the solution was much more simple (once i took a step back) - i was saving the treeindex into the DB just fine - but I didn't realize that I could just order the result set my saved treeIndex on the way out of the DB... the import functionality seems to consider the order of the flat list as a way to assign the treeindex order.

**Comment by NickEmpetvee** [comment]
@iamanidea I'm working on something similar. How did you extract the treeIndex value for a Node's current position? `getFlatDataFromTree` doesn't provide that, at least not in the storybook example.

**Comment by NickEmpetvee** [comment]
@iamanidea Also, when do you update the database? Are you updating it every time a tree node gets moved, and then pulling a fresh set of data back down from the tree?

**Comment by demifire** [comment]
@NickEmpetvee It looks like the `treeIndex` is included in `getFlatDataFromTree()`

As far as updating to database, this is something I'm still puzzled about. Did you happen to find a good way to do this? (Since your post was a while ago)

Cheers

**Comment by caoer** [comment]
getTreeFromFlatData did not sort the item correctly. you can use following function to do that. 
```
import { sortBy } from 'lodash';

      const sortAll = (tree: TreeItem[]) => {
        let sorted = sortBy(tree, ['treeIndex']);
        for (let index = 0; index < sorted.length; index++) {
          const item = sorted[index];
          if (Array.isArray(item.children)) {
            item.children = sortAll(item.children);
          }
        }
        return sorted;
      };
```
