### ISSUE TITLE
Issue with `npm run storybook`

### ISSUE THREAD

**Issue by NickEmpetvee** [fritz-c/react-sortable-tree#288]
I'm trying to run storybook with npm run storybook and getting the below error. The same happens if I run it with yarn or `npm run storybook --port 3001`. Please note that `npm start` works and properly launches a web server with the starter sortable tree and not the storybook som I'm only looking for help on the storybook. Looking for any suggestions anyone may have on this.

`C:\mcdev\react\react-sortable-tree-master>npm run storybook

> react-sortable-tree@2.1.0 storybook C:\mcdev\react\react-sortable-tree-master
> cross-env TARGET=development start-storybook -p ${PORT:-3001} -h 0.0.0.0

info @storybook/react v3.3.14
info
ERR! Error: port to run Storybook is required!
ERR!`

**Comment by wuweiweiwu** [comment]
I see. I will update the docs so that is more clear
