### ISSUE TITLE
Bringing this into existing application

### ISSUE THREAD

**Issue by NickEmpetvee** [fritz-c/react-sortable-tree#290]
If I want to import react-sortable-tree into an existing application how do I do it? What are the minimum files I'd need to copy into the other application?

**Comment by wuweiweiwu** [comment]
You would have to install via `yarn add react-sortable-tree` or `npm install react-sortable-tree --save`

and the [readme](https://github.com/fritz-c/react-sortable-tree/blob/master/README.md) has some demos!

**Comment by NickEmpetvee** [comment]
Thanks let me give that a shot.

**Comment by NickEmpetvee** [comment]
So that worked. Thank you! As I'm new to react, I'm experimenting. Can this only be added by NPM or YARN, Or can you copy the dist (main.js) somewhere in your application's directories and include it in your web page, along with locally stored react.js / react-DOM.js and babel.js files?

**Comment by wuweiweiwu** [comment]
yep! you can use with react using the npm or yarn package manager! It would be a dependency in your package.json

**Comment by NickEmpetvee** [comment]
Is there a way to use this without yarn or npm? Or are those the only ways? For example could I include your library `<script src="./react-browser-tree/main.js"></script>` in my HTML and start using this object?

**Comment by wuweiweiwu** [comment]
I do not believe so. Currently we only support usage through a package manager

**Comment by NickEmpetvee** [comment]
Ok thanks.
