### ISSUE TITLE
rowHeight problem

### ISSUE THREAD

**Issue by lionasp** [fritz-c/react-sortable-tree#34]
Hi, I have a problem with your plugin when I send the function like **rowHeight** props. I investigated that problem in https://github.com/fritz-c/react-sortable-tree/blob/master/src/react-sortable-tree.js#L360 when you send this props like **estimatedRowSize** props.
And in _react-virtualized_ package I found next code:
```
export default class List extends Component {
  static propTypes = {
    /**
     * Used to estimate the total height of a List before all of its rows have actually been measured.
     * The estimated total height is adjusted as rows are rendered.
     */
    estimatedRowSize: PropTypes.number.isRequired,

    /**
     * Either a fixed row height (number) or a function that returns the height of a row given its index.
     * ({ index: number }): number
     */
    rowHeight: PropTypes.oneOfType([PropTypes.number, PropTypes.func]).isRequired,
```
So **rowHeight** can be a function but **estimatedRowSize** don't. 
Can you fix this? Looks like you need to send some const value to **estimatedRowSize** props in _react-sortable-tree.js#L360_ against **rowHeight**. For example you can send **64 * rows.length** and it will work great

**Comment by fritz-c** [comment]
Sorry for the inconvenience. I had never tested using functions for `rowHeight` myself, but now that I'm getting into the swing of unit tests with components, I added that to the test cases. It should be fixed now in `v0.1.10`.

Thanks for pointing that bug out, and making this detailed issue!
