### ISSUE TITLE
Could u provide an example using reactVirtualizedListProps

### ISSUE THREAD

**Issue by coolguy001tv** [fritz-c/react-sortable-tree#35]
I want to use react-sortable-tree with list in [material-ui](http://www.material-ui.com/#/components/list), so I think it's best to use props `reactVirtualizedListProps`. But when I mostly copied code [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#prop-types) ,and put it into my page, it failed(No error happened in console but no effect either, the code I copied is ok if I just rendered it somewhere in that page).
Sorry my code is mess, I don't think it's great to put it here :(.
And  an example using reactVirtualizedListProps will help me a lot, thanks.

**Comment by coolguy001tv** [comment]
Or should I use `nodeContentRenderer`  to solve my problem?

**Comment by ekvalheim** [comment]
Example usage of reactVirtualizedListProps:
`
import SortableTree from 'react-sortable-tree';
<SortableTree
reactVirtualizedListProps={{ scrollToIndex: 200 }}
/>
`

**Comment by coolguy001tv** [comment]
It's really a long time, I can't even remember anything. So close it now.
