### ISSUE TITLE
Git example not working

### ISSUE THREAD

**Issue by 10SPD** [fritz-c/react-sortable-tree#39]
We are using the example code below from your main doc. It seems to throw the following errors. Any ideas what we are missing?

Cheers,
Mike 

```import React, { Component } from 'react';
import SortableTree from 'react-sortable-tree';

export default class BluePrint extends Component {
    constructor(props) {
        super(props);

        this.state = {
            treeData: [{ title: 'Chicken', children: [ { title: 'Egg' } ] }],
        };
    }

    render() {
        return (
            <div style={{ height: 400 }}>
                <SortableTree
                    treeData={this.state.treeData}
                    onChange={treeData => this.setState({ treeData })}
                />
            </div>
        );
    }
}```



```
ERROR in /Users/mikepriest/~/react-sortable-tree/dist/umd/react-sortable-tree.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-sortable-tree/dist/umd
 @ /Users/mikepriest/~/react-sortable-tree/dist/umd/react-sortable-tree.js 2:87-103

ERROR in /Users/mikepriest/~/react-dnd-scrollzone/lib/index.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-dnd-scrollzone/lib
 @ /Users/mikepriest/~/react-dnd-scrollzone/lib/index.js 16:13-29

ERROR in /Users/mikepriest/~/react-dnd-scrollzone/lib/index.js
Module not found: Error: Cannot resolve module 'react-dom' in /Users/mikepriest/node_modules/react-dnd-scrollzone/lib
 @ /Users/mikepriest/~/react-dnd-scrollzone/lib/index.js 20:16-36

ERROR in /Users/mikepriest/~/react-dnd/lib/DragDropContext.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-dnd/lib
 @ /Users/mikepriest/~/react-dnd/lib/DragDropContext.js 19:13-29

ERROR in /Users/mikepriest/~/react-dnd/lib/DragLayer.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-dnd/lib
 @ /Users/mikepriest/~/react-dnd/lib/DragLayer.js 19:13-29

ERROR in /Users/mikepriest/~/react-dnd/lib/decorateHandler.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-dnd/lib
 @ /Users/mikepriest/~/react-dnd/lib/decorateHandler.js 17:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/ArrowKeyStepper
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js 9:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/ArrowKeyStepper
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js 13:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/AutoSizer/AutoSizer.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/AutoSizer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/AutoSizer/AutoSizer.js 9:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/AutoSizer/AutoSizer.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/AutoSizer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/AutoSizer/AutoSizer.js 13:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/CellMeasurer/CellMeasurer.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/CellMeasurer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/CellMeasurer/CellMeasurer.js 9:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/CellMeasurer/CellMeasurer.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/CellMeasurer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/CellMeasurer/CellMeasurer.js 13:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/CellMeasurer/CellMeasurer.js
Module not found: Error: Cannot resolve module 'react-dom' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/CellMeasurer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/CellMeasurer/CellMeasurer.js 17:16-36

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/Collection.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Collection
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/Collection.js 11:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/Collection.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Collection
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/Collection.js 27:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Table.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Table.js 19:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Table.js
Module not found: Error: Cannot resolve module 'react-dom' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Table.js 23:16-36

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Table.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Table.js 25:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/defaultHeaderRenderer.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/defaultHeaderRenderer.js 8:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/defaultRowRenderer.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/defaultRowRenderer.js 11:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Column.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/Column.js 7:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/SortIndicator.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Table
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Table/SortIndicator.js 8:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/ColumnSizer/ColumnSizer.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/ColumnSizer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/ColumnSizer/ColumnSizer.js 9:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/ColumnSizer/ColumnSizer.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/ColumnSizer
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/ColumnSizer/ColumnSizer.js 11:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/InfiniteLoader/InfiniteLoader.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/InfiniteLoader
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/InfiniteLoader/InfiniteLoader.js 13:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/InfiniteLoader/InfiniteLoader.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/InfiniteLoader
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/InfiniteLoader/InfiniteLoader.js 15:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/List/List.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/List
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/List/List.js 15:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/List/List.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/List
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/List/List.js 23:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/MultiGrid/MultiGrid.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/MultiGrid
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/MultiGrid/MultiGrid.js 11:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/MultiGrid/MultiGrid.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/MultiGrid
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/MultiGrid/MultiGrid.js 15:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Grid/Grid.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Grid
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Grid/Grid.js 12:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Grid/Grid.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Grid
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Grid/Grid.js 40:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/ScrollSync/ScrollSync.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/ScrollSync
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/ScrollSync/ScrollSync.js 9:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/ScrollSync/ScrollSync.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/ScrollSync
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/ScrollSync/ScrollSync.js 11:33-72

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/WindowScroller/WindowScroller.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/WindowScroller
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/WindowScroller/WindowScroller.js 9:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/WindowScroller/WindowScroller.js
Module not found: Error: Cannot resolve module 'react-dom' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/WindowScroller
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/WindowScroller/WindowScroller.js 11:16-36

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/WindowScroller/WindowScroller.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/WindowScroller
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/WindowScroller/WindowScroller.js 15:33-72

ERROR in /Users/mikepriest/~/react-dnd/lib/wrapConnectorHooks.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-dnd/lib
 @ /Users/mikepriest/~/react-dnd/lib/wrapConnectorHooks.js 12:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/CollectionView.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Collection
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/CollectionView.js 11:13-29

ERROR in /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/CollectionView.js
Module not found: Error: Cannot resolve module 'react-addons-shallow-compare' in /Users/mikepriest/node_modules/react-virtualized/dist/commonjs/Collection
 @ /Users/mikepriest/~/react-virtualized/dist/commonjs/Collection/CollectionView.js 27:33-72

ERROR in /Users/mikepriest/~/react-dnd/lib/utils/cloneWithRef.js
Module not found: Error: Cannot resolve module 'react' in /Users/mikepriest/node_modules/react-dnd/lib/utils
 @ /Users/mikepriest/~/react-dnd/lib/utils/cloneWithRef.js 12:13-29
```

**Comment by fritz-c** [comment]
Do you have this first line from the example code?
```jsx
import React, { Component } from 'react';
```

I noticed another odd thing from your error messages - you seem to have a project folder of `/Users/mikepriest/~/`, but it's resolving your `node_modules` path to `/Users/mikepriest/node_modules`. Try renaming that `/Users/mikepriest/~/` folder to something like `/Users/mikepriest/my_project/`.
