### ISSUE TITLE
Port to React Native

### ISSUE THREAD

**Issue by Steviey** [fritz-c/react-sortable-tree#42]
Would it theoretically possible to port this to React Native?
What would be the steps?
Thank you.

**Comment by fritz-c** [comment]
I'm not sure, as I have never really used React Native before. I don't think the UI would work very well on a cramped screen, and drag-and-drop is dependent on a desktop environment at the moment.

If everything other than dnd works perfectly as-is, as unlikely as that seems, I suppose the [react-dnd-touch-backend](https://github.com/yahoo/react-dnd-touch-backend) package could be substituted in for the HTML backend by importing [`SortableTreeWithoutDndContext `](https://github.com/fritz-c/react-sortable-tree/blob/b07960a18dc8f7cf47480a216e9b85e8fa22b541/src/react-sortable-tree.js#L551) and applying it yourself. I've not tested the touch backend myself, so no guarantees there, either.
