### ISSUE TITLE
[Question] How can I use the path info when I am in onMoveNode

### ISSUE THREAD

**Issue by harris800** [fritz-c/react-sortable-tree#43]
Hi @fritz-c ,
Nice package. I am trying to get a destination index for the node in onMoveNode function, as readme says, I can get a treeData, an index, a path, and the node it self  as parameters when I call onMoveNode function. My problem is I try to get the node position I moved to, for example  `treeData[0].children[1].children[3]` is the new position of the node, so I want something like [0, 1, 3] to let me find the node in the new treeData. The path in the onMoveNode is including tree expanded node like [8, 13,  20]. Is there anyway I can omitting both hidden nodes and expanded nodes to create path?

Thank you!

**Comment by fritz-c** [comment]
Just to get a better idea of your issue, what is it that you want to do with that node once you can access it like `treeData[0].children[1].children[3]`?

**Comment by harris800** [comment]
@fritz-c I want to get the index of the node on it's new position on that level (like 3 in treeData[0].children[1].children[3] )to send back to database, so the database know where the node moved to.

**Comment by fritz-c** [comment]
Since you're using a DB, do you have unique ids tied to your nodes that you could use instead? If so, you could use a `getNodeKey` prop like so:

```js
// Supposing your nodes look something like:
// node = {
//     myUniqueId: 5,
//     parentId: 3,
//     title: 'My Title'
// };

// Render with getNodeKey and onMoveNode like so:
<SortableTree
    // ...
    getNodeKey={({ node }) => node.myUniqueId}
    onMoveNode={({ node, path }) => {
        const newParentId = path.slice(-2, -1);
        updateParentOnDb(node.myUniqueId, newParentId)
    }}
>

```

**Comment by harris800** [comment]
I see, I got your point. Will use the `getNodeKey ` to customize my path.
Thank you!
