### ISSUE TITLE
Problems with HTML5 Backend

### ISSUE THREAD

**Issue by romanmuska** [fritz-c/react-sortable-tree#44]
Hi everyone,

i start using React Sortable Tree and i get error "Cannot have two HTML5 backends at the same time.".. I am using it with React DnD so i think that both components use react-dnd-html5-backend so there is a problem. Does someone know how to solve it? Thanks.

**Comment by fritz-c** [comment]
Hi, thanks for trying out the component. Try using the react-dnd context you're already using along with the context-less exported component  [`SortableTreeWithoutDndContext `](https://github.com/fritz-c/react-sortable-tree/blob/b07960a18dc8f7cf47480a216e9b85e8fa22b541/src/react-sortable-tree.js#L551)

Something like:
```js
import { SortableTreeWithoutDndContext } from 'react-sortable-tree';
import { dragDropContext } from 'react-dnd';

// ...

const myReactDndContext   = dragDropContext(HTML5Backend);
const SortableTree        = myReactDndContext(SortableTreeWithoutDndContext);
const MyOtherDndComponent = myReactDndContext(OtherComponent);

// ... use them in render()
```

**Comment by fritz-c** [comment]
Going to treat this as closed due to inactivity.

**Comment by tsuz** [comment]
Thanks @fritz-c ! It worked for me as `import { DragDropContext } from 'react-dnd';`

**Comment by aterentev** [comment]
Hello!

I have the same problem.

App.js
```
import { DragDropContextProvider } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';

import ShowDirectoriesList from '../../containers/ShowDirectoriesList';

class App extends React.Component {
   render() {
       return (
           <DragDropContextProvider backend={HTML5Backend}>
               <Grid>
                   <Row className="show-grid">
                       <Col md={1} />
                       <Col md={5}>
                           <Panel className="explorer">
                               <ShowDirectoriesList />
                           </Panel>
                       </Col>
                       <Col md={6} />
                   </Row>
               </Grid>
           </DragDropContextProvider>
       );
   }
}
```

DirectoriesList.js

```
import SortableTreeWithoutDndContext from 'react-sortable-tree';

class DirectoriesList extends React.Component {
    render() {
        return (
            <SortableTreeWithoutDndContext
            // ...    
             />
        );
    }
}
```

With this code, when I tried to drag any element in the tree I got "Cannot have two HTML5 backends at the same time."

**Comment by fritz-c** [comment]
@aterentev Need to put brackets around the name in the import as follows:
```js
import { SortableTreeWithoutDndContext } from 'react-sortable-tree';
```

**Comment by aterentev** [comment]
Thanks @fritz-c ! It helps.

**Comment by wuweiweiwu** [comment]
@IvanGrodno this issue is already documented as a bug / more investigation. For future reference, its probably best to open a new issue or look if this issue already exists. 

Maintainers rarely check closed issues.
