### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by SergeyShablenko** [fritz-c/react-sortable-tree#45]
Is there a way to highlight some branch(es) of tree programmaticaly?

**Comment by fritz-c** [comment]
Try something like this out:
```js
<SortableTree
    // ...
    generateNodeProps={({ node, path, treeIndex }) => ({
        className: path[0] === targetNodeId ? 'my-highlight-class' : '',
    })}
/>
```
Note: you'll have to implement `my-highlight-class` yourself, and you'll probably want to use the `getNodeKey` prop so you have meaningful keys (like your object's unique id from a DB or something) in your `path`.
