### ISSUE TITLE
Problematic issue regarding sorting parents and child elements

### ISSUE THREAD

**Issue by chimanyans** [fritz-c/react-sortable-tree#46]
Dear friends 

I have noticed that every node can be moved to anyone.

But I need to make such way that parent node can be moved through the parent nodes(not into child nodes),

And the same for child nodes. Child nodes can be moved at the level of child nodes, no meter in which parent they are in. They can be moved from one parent child level into another parent's child nodes level.

**Comment by fritz-c** [comment]
I just released the `canDrop` API with version 0.1.13. I think this should help you do what you're trying to do.
