### ISSUE TITLE
Any way to set some rules for dropping?

### ISSUE THREAD

**Issue by HaykSim1** [fritz-c/react-sortable-tree#47]
I want to set some rules for dropping, for example I want to keep child in same level. I do not need ordering with changing levels. Any way?
  Thanks.

**Comment by fritz-c** [comment]
There's not a really good way to do this just yet. I've considered adding a `canDrop` method, but until a while ago I wasn't sure how to make it performant. I've got an idea I can try out whenever I get some free time.

**Comment by fritz-c** [comment]
I just released the `canDrop` API with version 0.1.13. I think this should help you do what you're trying to do.

**Comment by HaykSim1** [comment]
Hi.

We do that. I can create a pull request if you want :)

Best Regards.
Hayk

**Comment by fritz-c** [comment]
@HaykSim1 Pull request for what? If it's for an API to keep the child on the same level, it won't be necessary. I'm trying to keep the component as generic as possible right now, and sometimes focusing on common use cases.
