### ISSUE TITLE
Export ReactSortableTree

### ISSUE THREAD

**Issue by abhishiv** [fritz-c/react-sortable-tree#5]
Hey fritz-c

Thanks very much for the great module! I had been looking for something like this for long.

I wanted to check with you if you mind exporting ReactSortableTree.

This is needed to get around gaearon/react-dnd#186. In my case I'm using ctxhou/react-tabtab on the same page along with react-sortable-tree, and it throws this error.

If ReactSortableTree is exported I think I can pass in a custom DragDropContext as described in readme of react-tabtab .

**Comment by fritz-c** [comment]
This is fixed now thanks to #36. Thank you for providing the issue and information.
