### ISSUE TITLE
path in removeNode

### ISSUE THREAD

**Issue by vladimirsvsv77** [fritz-c/react-sortable-tree#51]
I try remove my Node, how I can get path in my case?
```
export default class TreeVera extends Component {
    constructor(props) {
        super(props);
        this.updateTreeData = this.updateTreeData.bind(this);
        this.removeNode = this.removeNode.bind(this);
        this.state = {
            treeData: [{
                title: (<div>
                        <input />
                        <button onClick={this.removeNode}>remove</button>
                    </div>),
            }]
        };
    }
    removeNode(e){
        this.setState({
               treeData: removeNodeAtPath({
                   treeData: this.state.treeData,
                   path: ????,
                   getNodeKey: ({node: TreeNode, treeIndex: number}) => {
                       console.log(number);
                       return number;
                   },
                   ignoreCollapsed: false,
               })
        })
    }
    updateTreeData(treeData) {
        this.setState({ treeData });
    }
    render() {
        return (
            <div style={{ height: 600 }}>
                <SortableTree
                    treeData={this.state.treeData}
                    onChange={this.updateTreeData}
                />
            </div>
        );
    }
}
```

**Comment by anil1712** [comment]
Try to use `generateNodeProps` to create `delete` button.
```
<SortableTree
     treeData={this.props.value}
     onChange={treeData => this.onChange(treeData)}
     generateNodeProps={rowInfo => ({
         buttons: [
                   <Button label='Delete'
                            onClick={(event) => this.removeNode(rowInfo)}/>,
                ],
      })}

removeNode(rowInfo) {
    let {node, treeIndex, path} = rowInfo;
    emoveNodeAtPath({
                   treeData: this.state.treeData,
                   path: path,   // You can use path from here
                   getNodeKey: ({node: TreeNode, treeIndex: number}) => {
                       console.log(number);
                       return number;
                   },
              ignoreCollapsed: false,
           })
}

```
**I am using the same way but some how getting below exception in browser console**
`Uncaught (in promise) Error: No node found at the given path.`
Let me know if its working for you

Thanks,

**Comment by vladimirsvsv77** [comment]
Thanks, your code works perfect!

**Comment by fritz-c** [comment]
@anil1712 Thank you for adding your code. I've been busy outside of work lately, so it helps when members in the community help out.

Regarding the node error, could you give me the stack trace and steps for reproduction?

Your code looks like it would work except for one part - the result of `removeNodeAtPath` needs to be used to update `this.state.treeData` in your component.

**Comment by anil1712** [comment]
Thanks for reply @fritz-c 
Now its also working for me.

**Comment by GayathriVenkatesan93** [comment]
Hello, Can anyone please help with this and how to remove any node in the tree. Why because means I was trying the above same code in the functional component and got the error like this 

Error: No node found at the given path.

**Comment by hungnguyen1412** [comment]
@fritz-c can you help me with this issue?
I'm try to delete a node like that:
```
const _newTreeData = removeNodeAtPath({
      treeData: treeData,
      path: myPath,
      getNodeKey: ({ treeIndex }) => treeIndex,
      ignoreCollapsed: false
    })

    setTreeData(_newTreeData)
```

**Comment by nguyenthuc** [comment]
@hungnguyen1412  
You can to set newNode : {... currentNode, ItemNode },
removeNodeAtPath({
      treeData: treeData,
      path: myPath,
      getNodeKey: ({ treeIndex }) => treeIndex,
      newNode: { ...currentNode, ItemNode },
      ignoreCollapsed: false
    })
Working for me

**Comment by gokulprathin8** [comment]
@hungnguyen1412 
removing a node from one place to another carries its path value, and when we perform an operation such as removeNodeAtPath, the function is not able to find the node at the given path.
