### ISSUE TITLE
Question: Rerender tree when I add/delete a node

### ISSUE THREAD

**Issue by harris800** [fritz-c/react-sortable-tree#54]
Hi @fritz-c,
I met an issue here, my code can work fine on drag, collapse, expand. I set treeData to read this.state.treeData. My issue is when I add/delete a node in treeData and set treeData to use new treeData by call this.setState({treeData: newTreeData}). I can see when render, the state is already changed. But the tree won't update until I collapse the parent and expand again, then the node will add/remove. Did I missed anything here? I tried to call forceUpdate() at setState's callback, but no lucky here.
Thanks.

**Comment by fritz-c** [comment]
It could be that react doesn't detect the object/array change. I believe that can happen if you edit your object/array in-place.
So if you're adding via methods like:
```js
const newTreeData = this.state.treeData;
newTreeData.push({title: 'myNewNode'});
// or
newTreeData[0].children = [{title: 'child1'}, {title: 'child2'}];
this.setState({treeData: newTreeData}); // won't update
```
you should instead use methods like
```js
const newTreeData = this.state.treeData;
newTreeData = newTreeData.concat({title: 'myNewNode'});
// or
newTreeData = [
    {...newTreeData[0], children: [{title: 'child1'}, {title: 'child2'}]} // requires babel-plugin-transform-object-rest-spread
].concat(newTreeData.slice(1));
this.setState({treeData: newTreeData}); // will update
```
All the data manipulation methods (including node addition/removal) included in this package behave like the second bunch of examples, so if you're using those and still have a problem it might be something else.

**Comment by harris800** [comment]
Hi @fritz-c,
Thanks for your advice, I got the point. I am using _.merge method and it mutates object, that's why it is not update. Thanks!

**Comment by anil1712** [comment]
Hi,
I am using the same, its working fine but at the end the whole tree collapsed. I tried to pass `expanded` in new node but seems not working.

Thanks,
