### ISSUE TITLE
Question about versions of peer dependencies

### ISSUE THREAD

**Issue by suriya** [fritz-c/react-sortable-tree#56]
I have a question on the `peerDependencies` definition in the `package.json` file. I find that the dependency version is specified as a single version rather than a range. https://github.com/fritz-c/react-sortable-tree/blob/0953ffa206cf3cb9bdc4e632bfd1178d3fe4711b/package.json#L40 For example, `"react": "^15.3.0",`. I think this should be modified to allow more flexibility in the versions that a developer may use.

**Comment by fritz-c** [comment]
The caret makes it a range, so I think it's fine for now.
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

`^15.3.0` is equivalent to `>=15.3.0 <16.0.0`

**Comment by suriya** [comment]
Thank you for the quick response. I had mistakenly assumed it was only `>=15.3.0 <15.4.0`.

**Comment by fritz-c** [comment]
No problem! I appreciate your interest in making the library better.
