### ISSUE TITLE
How to lock dragging of element to its depth only?

### ISSUE THREAD

**Issue by ppkinev** [fritz-c/react-sortable-tree#57]
Hi!

I have pretty nested structure in the project, simplified version looks something like this:

+block 1
--questions
----question 1
----question 2
----question 3
--answers
----answer 1
----answer 2
----answer 3

and so on. 

So would be great to specify drag zone to move questions within its container only (block 1 -> questions). Could you point me where to look in order to add such feature?

Thanks.

**Comment by AaronHarris** [comment]
Looks like this issue is solved with #70?

**Comment by fritz-c** [comment]
True. Thanks for the heads-up @AaronHarris. Closed via #70.
