### ISSUE TITLE
[Feature Request] Single-Root Tree

### ISSUE THREAD

**Issue by cpunion** [fritz-c/react-sortable-tree#58]
Sometimes I need a single-root tree, likes https://github.com/pqx/react-ui-tree/, I tried in `react-sortable-tree` but no idea. I can ignore it in onChange, but isn't good experience. How about support it?

**Comment by fritz-c** [comment]
Could potentially be solved by a fix to #52

**Comment by fritz-c** [comment]
This can now be accomplished with the canDrop prop.
