### ISSUE TITLE
Fix appearance in IE 9

### ISSUE THREAD

**Issue by fritz-c** [fritz-c/react-sortable-tree#6]
I had the styles working well in IE 9 (which cannot use flexbox) until a short while ago, when something apparently broke it.

**Comment by rturk** [comment]
@fritz-c No sure if IE 9 support is really necessary given decading IE 9 usage. Lack if flexbox support makes this quite complex.

**Comment by fritz-c** [comment]
Technically, IE 9 has extended support until April 2017. It's because Vista extended support ends then, and IE 9 is the latest version you can get on that. I even have that date set on my personal calendar (Unofficial Start of Flexbox Day).
I'm not aiming to make it work perfectly, but I actually had the positioning working pretty well before I put in the flexbox stuff. It shouldn't take much to get it back to that state again.

**Comment by topher515** [comment]
Anyone have insight into what was the last version in which IE9 still worked?

Unfortunately my team still has to support it so, +1 for fixing it in IE9.

**Comment by fritz-c** [comment]
@topher515 I got the basic appearance working on it with v0.1.4, but in my tests (on a remote machine) the performance was less than spectacular, and the landing pad (the blue / red area displayed when hovering) wasn't displaying for some IE reason. Usability-wise, I don't think anything's broken beyond use. It's just not great.

**Comment by enniel** [comment]
You can add support using [flexibility polyfill](https://github.com/jonathantneal/flexibility)

**Comment by fritz-c** [comment]
@enniel Thank you for the suggestion. However, as the end of support for IE 9 is only a couple months from now, and I haven't had too many requests concerning it, I think I'll be leaving the IE 9 compatibility as-is.
