### ISSUE TITLE
add new nodes from a list

### ISSUE THREAD

**Issue by cocodrino** [fritz-c/react-sortable-tree#60]
Hi, I've a small project where I've a list of items and I need than they can be dragged for build a tree..like

```js
item1
item2
item3
item4
```
drag to create

```js
item2
  |
    item1
     |
      item2
      item3
        |
        item4
        item1


```

do you think than this could be possible using react-sortable-tree?

thank you so much

**Comment by cpunion** [comment]
Need too.

**Comment by fritz-c** [comment]
I don't quite understand your question. Do you want to
1. Create a tree based on an array of nodes?
2. Add nodes to an existing tree from an array?
3. Do drag-and-drop actions that duplicate your nodes sometimes? (Your example tree has two each  of item1 and item2)

**Comment by cocodrino** [comment]
hi @fritz-c basically I need have a list (array of nodes) then could drag and build a tree, don't care about if repeat some nodes, imagine an html tag list and build an html document tree drag and drop elements, so yes, you can have several img or p elements

**Comment by fritz-c** [comment]
@cocodrino One issue you might run into is that the rows are fixed-height. If you're considering using images, I think that would cause problems for you. However, if that's not an issue, I believe this library would serve as a good base for what you want to do.

To get a better idea for yourself, try out the [demo](https://fritz-c.github.io/react-sortable-tree/) and check out the [demo code](https://github.com/fritz-c/react-sortable-tree/blob/master/src/examples/basicExample/app.js).

**Comment by cpunion** [comment]
I need drag a component from the component list panel into the DOM tree panel to add the component to DOM tree. When the component is dragging, it likes a tree node that can move in tree, but when drop it out of the DOM tree, don't add it (remove it).

I guess @cocodrino same as me, item1 ... item4 are the components, drag them into the tree can build the tree.

**Comment by cpunion** [comment]
@fritz-c And how to duplicate node by dragging? (maybe need press a modifier key)

**Comment by fritz-c** [comment]
@cpunion Tree-to-tree dragging is not possible at this time (see #29). As for duplicating, there are no convenience functions to do it, but you could potentially implement it yourself by modifying the `treeData` in the `onMoveNode` callback prop.

**Comment by cpunion** [comment]
@fritz-c For experience, I think it can't use in my project. I need a experience likes #64.

Tree is very complex, no more good alternates. This library is already good enough, thanks again. :-)

**Comment by fritz-c** [comment]
I think I understand the motive of this question better now. If you want to drag an element in from another list, you can do something like this example:
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Drag%20from%20external%20source&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

If you want to drag from one tree to another, check out this example:
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Tree-to-tree%20dragging&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

**Comment by bhupendrarawat1973** [comment]
@fritz-c - How we can we deploy the same components on O365 tenant ?

**Comment by nmartinezb3** [comment]
@fritz-c  could you please provide a new link with the example of dragging an element in from another list?

Thanks
