### ISSUE TITLE
How to change title of a node dynamically

### ISSUE THREAD

**Issue by thewebsitedev** [fritz-c/react-sortable-tree#61]
Hello,

I would like to use an input field for title so that user can change the title if required. Adding input field is easy but how to save the value?

**Comment by fritz-c** [comment]
Add an `onChange` attribute to that input.

**Comment by thewebsitedev** [comment]
Yes, I have done that but then how to save that value to that specific node?

**Comment by thewebsitedev** [comment]
Got it to work. Thanks!

**Comment by AaronHarris** [comment]
@thewebsitedev When you have an answer to your question, it's helpful if you share the code you used for others to learn from!

**Comment by thewebsitedev** [comment]
@AaronHarris I know but I actually modified react-sortable-tree quite a bit and so it might not work for other users. I will try to provide an example when I get some time.

**Comment by Ccheng2729111** [comment]
@thewebsitedev  so can you show your code,i really want to know how to save the value when i  use an input field for title..thanks!

**Comment by ChathurangiShyalika** [comment]
I have the same issue. Can you please mention how you solved  it?
