### ISSUE TITLE
prevent scrolling when nodes get expanded or collpsed

### ISSUE THREAD

**Issue by spookyfox** [fritz-c/react-sortable-tree#63]
Hi,

I really appreciate your tree, great job !

I would like to know if the scrolling behavior ist standard or can be stopped. When a node gets expanded or collapsed the screen scrolls automatically which is not really desired.

Any help would be much appreciated.

Cheers,
Henrik

![image](https://cloud.githubusercontent.com/assets/14878872/23865303/8f9149c6-0815-11e7-9e97-79c6b8149d7d.png)

![image](https://cloud.githubusercontent.com/assets/14878872/23865321/96818408-0815-11e7-8195-441d7c7738f7.png)

**Comment by fritz-c** [comment]
Hmm... That certainly isn't a desirable behavior.

Can you tell me what props you have set on the component, and if it is full-screen / in a scrollable div / not using virtualization (`props.isVirtualized` = `false`)?

To explain a bit, the scrolling behavior on collapse is not being customized. The collapsed rows are simply not being rendered any more. There's a very minor chance that something in react-virtualized could affect the scrolling, but I've not had anything unexpected with it happen thus far.

**Comment by spookyfox** [comment]
hi fritz-c, Thanks for replying such fast. Meanwhile I came to the conclusion that my hardware causes this issue, since most of the times it work really well! Thanks again for sharing this quite cool component.

But I would have another question: would it be possible e.g. to grap an item from another instance of the tree and place it underneath any node there. Means drag and drop from another, second source-tree or list?

**Comment by fritz-c** [comment]
Tree-to-tree dragging is now available in version 1.0.0. See the example in the storybook for how to use it:
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Advanced&selectedStory=Tree-to-tree%20dragging&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel
