### ISSUE TITLE
Issue with last element and canDrop

### ISSUE THREAD

**Issue by Frit** [fritz-c/react-sortable-tree#68]
Hi, you can reproduce it on demo page
https://fritz-c.github.io/react-sortable-tree/

Go to the end of the list, open Advanced, move <When node contents are really..> to <Depth 4>
and hover <Depth 4> on the child list, move mouse about 5 sec(with dragged <Depth 4>), background turns red all is well, but when you will drop <Depth 4> module will freeze(for a while). 

Or look at Gif.
[gif 1](https://media.giphy.com/media/xUA7aRp5EvqlXrAYrm/source.gif)
 So I've reproduced it on my local sever and I've added to canDrop function console.log

```
function canDrop(dropTargetProps, monitor) {
                var isHover = arguments.length > 2 && void 0 !== arguments[2] && arguments[2], abovePath = [], aboveNode = {}, rowAbove = dropTargetProps.getPrevRow();
                rowAbove && (abovePath = rowAbove.path, aboveNode = rowAbove.node);
                var targetDepth = getTargetDepth(dropTargetProps, monitor), draggedNode = monitor.getItem().node;
                // Either we're not adding to the children of the row above...
                // ...or we guarantee it's not a function we're trying to add to
                // ...unless it's at a different level than the current one
                var canDrop = !(!(targetDepth < abovePath.length || "function" != typeof aboveNode.children) || dropTargetProps.node === draggedNode && isHover === !0 && targetDepth === dropTargetProps.path.length - 1)

                console.log('canDrop?: ' + canDrop);

                return canDrop;
            }
```

One more gif
[gif 2](https://media.giphy.com/media/l1BgSLJ7c6zvsB5D2/source.gif)
As you can see canDrop is true (although it should not be so).

Windows 7
Chrome 56.0.2924.87 (64-bit)
FF 52.0 (32-bit)
ps: also have tested on win10 and osx 10.12.2 (same browsers), works fine.

**Comment by Charles-521** [comment]
It works on the demo site now but the latest release still has this issue (0.1.20), curious about which branch is used by demo site

**Comment by fritz-c** [comment]
This should be fixed as of the latest release.
