### ISSUE TITLE
Numbered expand and collapse button

### ISSUE THREAD

**Issue by hsellou** [fritz-c/react-sortable-tree#79]
Hello,

I want to custom the expand and collapse button in order to have numbers corresponding to the expansion level. Is it possible by tweaking the css ?

Something like that:
![image](https://cloud.githubusercontent.com/assets/12375749/24765624/caa1e016-1af8-11e7-902d-b93691039345.png)

Far now, I can have arrows instead of 'plus' and 'minus' button with the `rst__collapseButton` and `rst__expandButton` classes but I can't get the expansion level :(

**Comment by fritz-c** [comment]
Sorry for the long delay. I would suggest a solution using CSS counters:
https://www.w3schools.com/css/css_counters.asp

**Comment by hsellou** [comment]
Thank you but I surrendered and I implemented a custom node renderer :)

By the way, can you add a sample showing how to create a node renderer.
I had difficulties to start :(

**Comment by shaikhussian** [comment]
@hsellou did you find any solution

I also want something like how you want

here is my sample design how it needs to look

![Screenshot 2019-11-17 at 9 12 42 PM](https://user-images.githubusercontent.com/11956308/69017876-8b68c180-09cf-11ea-8a7f-d477e553addd.png)
