### ISSUE TITLE
Tree doesn't propagate all properties to custom node renderer

### ISSUE THREAD

**Issue by Mindtoeye** [fritz-c/react-sortable-tree#81]
When I assign a custom node renderer (an almost direct copy of the one used by the tree code itself) I'm only getting the following properties in the render function: 

- node
- path
- lowerSiblingCounts
- lowerSiblingCounts
- isSearchMatch
- isSearchFocus

For example:

```
{
    "node" : {
        "orgType" : "Skill",
        "title" : "New Skill",
        "id" : "749da3d3-0067-4047-82af-1880a15c5740",
        "skillModel" : {
            "sType" : "BKT",
            "pGuess" : 0.1,
            "pKnown" : 0.25,
            "pSlip" : 0.1,
            "pMastery" : 0.95
        }
    },
    "path" : [0],
    "lowerSiblingCounts" : [0],
    "treeIndex" : 0,
    "isSearchMatch" : false,
    "isSearchFocus" : false
}
```

**Comment by fritz-c** [comment]
Can you tell me what other properties you would expect it to have?

**Comment by Mindtoeye** [comment]
One of the items that gets propagated properly when I do not assign a custom renderer is canDrag, which internally is used to determine if the gripper is displayed and used.

I'm not sure if it's relevant but I'm rebuilding the custom node renderer to operate in a TypeScript environment.

**Comment by fritz-c** [comment]
Are you assigning the custom renderer to `nodeContentRenderer`? Based on those values provided it looks more like the parameters to the function set to `generateNodeProps`.

**Comment by Mindtoeye** [comment]
Yes very sure. 

In fact I am using the generateNodeProps in one of the three instances where I need a sortable tree and it works just fine. The props generated by my function are properly propagated to the renderer. 

Although I haven't figure out how to use it to pass event handlers down to the renderer. 

But even then I don't see the full list of properties I would expect.

**Comment by fritz-c** [comment]
What version are you using?

**Comment by Mindtoeye** [comment]
In our package.json I've got it set to: "react-sortable-tree": "^0.1.12"

**Comment by fritz-c** [comment]
Sorry for the silence. Did you figure out a solution in the end?

**Comment by Mindtoeye** [comment]
We dropped looking into it since we were on a deadline and found that for our purposes we could hard-code some of the values.

**Comment by fritz-c** [comment]
Ok, I'm going to close this for now and see if it comes up again.
