### ISSUE TITLE
A way to set noDragging on whole tree

### ISSUE THREAD

**Issue by robhadfield** [fritz-c/react-sortable-tree#82]
Hi all - I'm have a tree that has an editable and uneditable state.

I can set `canDrop={() => false }` which stops any dragging but the handles are still there...  I can also set `noDragging=true` to an individual node and this removes the handle (desired behaviour)

Is there a way to set `noDragging` to all nodes without adding the prop to each node object?

Thanks in advance.

**Comment by fritz-c** [comment]
Setting `canDrag={false}` to the component should do it. The value `canDrag={({ node }) => !node.noDragging}` in the demo was just for demonstration purposes.

**Comment by robhadfield** [comment]
Ah brilliant, I was using the `noDragging={true}` prop. Sorted - many thanks :)
