### ISSUE TITLE
Tree doesn't update when title is 'input'

### ISSUE THREAD

**Issue by vladimirsvsv77** [fritz-c/react-sortable-tree#84]
Hi, @fritz-c! thank you for the component!
I customize NodeRendererDefault, replace `<span>` by `<input>` in field 'title'.
When I move nodes, input value doesn't move with them. 

my title: 
```
    <input
        className={styles.rowTitle +
            (node.subtitle ? ` ${styles.rowTitleWithSubtitle}` : '')
        }
       onChange={this.updateInput}

       defaultValue= {typeof node.title === 'function' ?
            node.title({node, path, treeIndex }) :
            node.title
        }
    />
```
function updateInput:
```   
    updateInput(e){
        console.log(e);
        console.log(e.target.value);
        this.props.node.value = e.target.value;
        console.log(this.props.node.value);
    }
```

**Comment by fritz-c** [comment]
You have some code that is not doing things in a React-best-practices sort of way (e.g. directly modifying props). It will take a fair bit more code to do it the right way, but check for now if changing defaultValue to value in the props, and node.value to node.title in updateInput, works.

**Comment by vladimirsvsv77** [comment]
Thanks! I added `value={node.value}` in input and all works.
