### ISSUE TITLE
Update react-dnd dependency

### ISSUE THREAD

**Issue by kallaspriit** [fritz-c/react-sortable-tree#87]
Should solve "Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

**Comment by eMarek** [comment]
@fritz-c any plans about updating react-dnd dependency?

**Comment by fritz-c** [comment]
The dependency in `package.json` is `^2.1.4`. This should allow for the downloading of the current version (`2.4.0`) of `react-dnd`, as far as I understand. I believe the source of the warning lies in [`react-dnd-scrollzone`](https://github.com/azuqua/react-dnd-scrollzone). I'll communicate with the author to try to get it fixed.

**Comment by fritz-c** [comment]
https://github.com/azuqua/react-dnd-scrollzone/pull/14

**Comment by eMarek** [comment]
It was merged. Thank you @fritz-c!
