### ISSUE TITLE
Scrolling acceleration

### ISSUE THREAD

**Issue by vpachedzhi** [fritz-c/react-sortable-tree#89]
I recently updated to the last version 0.1.17 and noticed that scrolling is much faster than my previous one (0.1.7). That causes flickering and blank spaces for several seconds. I tried to lower the overscanRowCount but the problem still exist when the scrolling is fast. Is there a way to slower the scrolling acceleration ?

**Comment by fritz-c** [comment]
This would be more of a react-virtualized issue, but I think you might be able to mitigate it by _increasing_ the `overscanRowCount`. Please try that out.

**Comment by vpachedzhi** [comment]
The problem was in my custom node renderer. I had a time consuming operation. Now with the last version of the tree and optimization in my code the scrolling is really fast and there is no flickering in Chrome. In Firefox I cannot accelerate the scrolling so I cannot have flickering even with slow node renderer so may be react-virtualized has different behavior in different browsers but it is still good.
One problem I also found is that when dragging a node it disappears(only the blue area is seen) if I have a matrerial-ui icon with a tooltip property on it in my node renderer. When there is no tooltip the node can be seen.
