### ISSUE TITLE
Hide non-matching items in search

### ISSUE THREAD

**Issue by fritz-c** [fritz-c/react-sortable-tree#9]
From #8:
> Another quick question. With the search function- is it possible that it "Hides" items which don't match the search? This could be a clean way to arrange similar items?

**Comment by fritz-c** [comment]
It would be possible, but there are a couple of issues that go along with that.

1. If we hide all of the non-matching nodes, the visual structural information is lost or at the very least jumbled.
2. If we include just the line of ancestry (all the parents) of any matched node to preserve the structural information, we are still potentially left with many excess nodes that distract from the matched nodes.

I suppose the solution of 2. is the most reasonable, but I'm not sure the benefits justify the cost (extra complexity and time).

**Comment by yarnball** [comment]
Thanks. I see the problem with this. I don't think it's worth a high priority for the project 👍

**Comment by fritz-c** [comment]
Ok, thanks for the feedback!
