### ISSUE TITLE
npm install --save react-sortable-tree doesn't work as expected

### ISSUE THREAD

**Issue by AnirudhVyas** [fritz-c/react-sortable-tree#90]
I have a small react project where I was using autocomplete successfully with react-sortable-tree, but now when i try and build the project i get these kinds of errors -
```
ERROR in ../react-sortable-tree/~/dnd-core/lib/HandlerRegistry.js
Module not found: Error: Can't resolve 'asap' in '/Users/anirudh.vyas/git_staging/react-sortable-tree/node_modules/dnd-core/lib'
```

What could I be missing?

**Comment by fritz-c** [comment]
Have you tried deleting your `node_modules` directory and installing again?

**Comment by fritz-c** [comment]
Closed due to inactivity.
