### ISSUE TITLE
Table header

### ISSUE THREAD

**Issue by michaeltrilford** [fritz-c/react-sortable-tree#92]
Has a concept of a table header been explored for use with this component?

**Comment by fritz-c** [comment]
Can you elaborate on what the header would be used for?

**Comment by michaeltrilford** [comment]
Hey mate, thanks for the quick response. I will create a mock-up to help communicate the request, and maybe you can provide some thoughts.
<img width="569" alt="screen shot 2017-05-13 at 12 13 43 pm" src="https://cloud.githubusercontent.com/assets/2483515/26021658/acc40e8a-37d5-11e7-8da3-801ccee85ca8.png">

**Comment by fritz-c** [comment]
It's kind of a special use case, so I think you'd be better off putting a div above the component with your header info, and doing the rest of the styling via a custom node renderer.
