### ISSUE TITLE
Editing Node

### ISSUE THREAD

**Issue by hrachmkr** [fritz-c/react-sortable-tree#93]
Hi

How can I change node's title? I've added changeNodeAtPath function but it's actually replace the node. So I want to change the title at the given path and not to replace with new node. Thanks))

**Comment by Ccheng2729111** [comment]
i have the same question..~

**Comment by fritz-c** [comment]
I've recently put together an example in the storybook doing this exact this exact thing. Please see the "Modify Nodes" example and its source. 
https://fritz-c.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Modify%20nodes&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Fnotes%2Fpanel

**Comment by gduquesnay** [comment]
@fritz-c Storybook link you provided above is broken now.  Could you update it?

**Comment by fritz-c** [comment]
@gduquesnay Done. Thanks for the heads up.

**Comment by alijarar** [comment]
Storybook link you provided above is still broken. Could you update it?

**Comment by deepikaarava** [comment]
https://frontend-collective.github.io/react-sortable-tree/storybook/?selectedKind=Basics&selectedStory=Modify%20nodes&full=0&addons=0&stories=1&panelRight=0

this link is broken, I need this please help me with correct link

**Comment by vassilyvv** [comment]
Hi,

I have to implement complicated tree view with several editable fields for each node but I didn't find any documentation for even one field. It would be great to see at least code of [this](https://frontend-collective.github.io/react-sortable-tree/iframe.html?id=basics--modify-nodes) sample.

**Comment by metalalive** [comment]
All links above are broken , but you can edit any node by following steps : 
* get the node from `getNodeAtPath()`
* edit the fields of the node
* refresh the tree view by calling `your_react_component.setState({treeData: YOUR_TREE_DATA})`

For code example please check out [this answer on stackoverflow](https://stackoverflow.com/a/66857970/9853105)
