### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by GitShaffi** [fritz-c/react-sortable-tree#94]
Getting the above warning in **DragDropContext** from '**react-dnd**'. Please upgrade the react library and import right propTypes.

**Comment by GitShaffi** [comment]
This issue has been fixed in react-dnd. Please upgrade to latest version of **'react-dnd'**.

**Comment by fritz-c** [comment]
I believe this is fixed now.
