### ISSUE TITLE
Scrolling too much

### ISSUE THREAD

**Issue by brunont** [fritz-c/react-sortable-tree#95]
Hi,

When we display the react-sortable-tree at smaller widths and drag and drop until the right limit, the screen scrolls too much and user is unable to go back to the tree. See example below:

![bug-dnd-width3](https://cloud.githubusercontent.com/assets/68289/26205800/3ad47d04-3bb9-11e7-9e18-e5c0eec2eab5.gif)

**Comment by fritz-c** [comment]
This looks like a side effect of using `Autosizer` from `react-virtualized`. Does the issue persist if you have the width set to something small since before the component is rendered?

**Comment by brunont** [comment]
yes:

![dnd2222](https://cloud.githubusercontent.com/assets/68289/26232524/47d61ba6-3c2d-11e7-834c-d2046c07493a.gif)

**Comment by fritz-c** [comment]
Yeah, that looks like a bug.
