### ISSUE TITLE
Question: Auto-scroll to bottom of list

### ISSUE THREAD

**Issue by AdaptiveChar** [fritz-c/react-sortable-tree#98]
I've got a long list of tree node, and when adding a new item it would ideally scroll to the bottom of the list to display the new item. 

I'm thinking this would work similarly to the scrolling used for the filters, but not exactly. Has anyone tried and had any luck with this?

**Comment by fritz-c** [comment]
There is a react-virtualized prop that will scroll it down to a specified row index. Inject that via the reactVirtualizedListProps prop on the tree component.

**Comment by fritz-c** [comment]
Treating this as closed due to inactivity.
